### ISSUE TITLE
Saving a project doesn't work

### ISSUE THREAD

**Issue by sylwiabr** [luna/luna-studio#1001]
with a project like:
```
def main:
    a = 10
        b = 12
    None
```
and press ctrl+s you will get a save error

**Comment by mikusp** [comment]
@pmlodawski I tested this on Linux right now, and while I can save a project successfully, it will reopen with graph at the top level, not in `main` function as it was. I think it's wrong behaviour.

**Comment by mikusp** [comment]
Tested this on 1.3.0.1 and indeed, after saving project is opened on the top level.

**Comment by sylwiabr** [comment]
should work since LunaStudio 1.4
