### ISSUE TITLE
Class added after the `main` method is not in scope

### ISSUE THREAD

**Issue by piotrMocz** [luna/luna-studio#1003]
Which leads to errors like the following: ![obraz.png](https://images.zenhubusercontent.com/5967836b61b4ca3b0a74517c/d7e1be63-bc7d-45a1-afb2-8f83c017c9c6)

**Comment by mikusp** [comment]
Fixed by https://github.com/luna/luna-studio/commit/3679347fdabcbea34fdaa787c8f333d9c2451e7e? @piotrMocz

**Comment by piotrMocz** [comment]
I hereby accept this task as done. Moving to the `To Release` column. Re-assigning @kustosz to give him the credit for solving ;)

**Comment by sylwiabr** [comment]
should work since LunaStudio 1.4
