### ISSUE TITLE
Parser error on classes added before the `main` method.

### ISSUE THREAD

**Issue by piotrMocz** [luna/luna-studio#1004]
Please see the screenshot: ![obraz.png](https://images.zenhubusercontent.com/5967836b61b4ca3b0a74517c/931c1404-7dbf-4c65-88c8-6b657b3e0f16)

This is really bad, because connected with the issue #1003 it prevents the user from defining classes altogether.

**Comment by piotrMocz** [comment]
Same thing applies to functions:
<img width="814" alt="obraz" src="https://user-images.githubusercontent.com/3109645/43266152-ecd3e30a-90ea-11e8-89d5-ae08f32b6d4c.png">

**Comment by mikusp** [comment]
Could be caused by luna/luna-core#128

**Comment by wdanilo** [comment]
Fixed in new parser
