### ISSUE TITLE
Improper invalid on `foo =`

### ISSUE THREAD

**Issue by piotrMocz** [luna/luna-studio#1007]
```python
def main:
    hello = "Hello World"
    None
```
and now we create a new line between `hello` and `None` and start typing:
```python
def main:
    hello = "Hello World"
    foo =      ### that's all we managed to type so far
    None
```
and poof, the graph disappears.
```python
    hello = "Hello World"
    foo =  ""  ### we add the quotes to make a valid expression
    None
```
and the graph is visible again.

Is this the desired behavior?

**Comment by mikusp** [comment]
No, this is not the desired behaviour. Node foo should be marked as invalid
instead.

pt., 27 lip 2018, 12:49 użytkownik piotrMocz <notifications@github.com>
napisał:

**Comment by mikusp** [comment]
I found out that parser returns here `Invalid FunctionBlock` for main, instead of only invalidating `foo`. Reassigning to @wdanilo

**Comment by wdanilo** [comment]
Fixed in new parser
