### ISSUE TITLE
Windows - You do not have permission to create the package, after creating New Project

### ISSUE THREAD

**Issue by lgawlik** [luna/luna-studio#1009]
On Windows 10

1) Click New Project
2) Go back to welcome screen
3) Clicking New Project again is not possible (button is disabled)
4) Click some of the examples, for exampel Ellection Playground
4) Example is opened with error:
Error
You do not have permission to create the package: C:\Users\Łukasz Gawlik\AppData\Local\Temp\luna9196\UnsavedLunaProject

while processing event

**Comment by sylwiabr** [comment]
@lgawlik can you confirm it is fixed in Luna studio 1.4?
