### ISSUE TITLE
Error while cloning tutorial

### ISSUE THREAD

**Issue by lgawlik** [luna/luna-studio#1010]
1) Open USElectionPlayground
2) Go back to welcome screen
3) Open USElectionPlaygorun, there is an error: Error while cloning tutorial
![Errorwhilecloningtutorial.png](https://images.zenhubusercontent.com/5b15567389d5dc41604fd216/1a198ad5-f548-472b-8381-d0779243e993)

**Comment by mikusp** [comment]
Duplicate of #1006
