### ISSUE TITLE
Recompute button works only once

### ISSUE THREAD

**Issue by kustosz** [luna/luna-studio#1011]
When I use it the first time, all is fine, but then it becomes inactive. Cursor changes the state too, indicating the button can't be clicked:

<img width="576" alt="screen shot 2018-07-29 at 22 51 05" src="https://user-images.githubusercontent.com/1214109/43370589-e83ed694-9381-11e8-9460-148c1951a593.png">

**Comment by sylwiabr** [comment]
should work since LunaStudio 1.4
