### ISSUE TITLE
Code disaapears with strange error on undo.

### ISSUE THREAD

**Issue by pmlodawski** [luna/luna-studio#1013]
1. Open new project
2. Click on code editor
3. Press Ctrl+z
4. Code disapears and error is raised: 
```
Breadcrumb {_items = [Definition {_nodeId = 7ce7d739-eb0b-48e2-a413-d20ce6f9364b}]}

while processing event

empire.atom.file.substitute.response
```

When you continue editing this file, more strange things are happening

**Comment by piotrMocz** [comment]
Unable to reproduce on 4d5d8f55bc5765c9fc5bf941d41d9653ab3fa5b2 (master, MacOS High Sierra 10.13). I can Cmd+z and Cmd+Shift+z back and forth and everything works as expected, no errors.
