### ISSUE TITLE
BreadcrumbDoesNotExist & state mismatch when removing current scope from text editor.

### ISSUE THREAD

**Issue by kustosz** [luna/luna-studio#1015]
Repro:
1. Create new project.
2. Select & remove the `main` function in text editor.
3. Results:
3a. Immediately "Breadcrumb does not exist exception"
3b. The text is still removed from text editor.
3c. The graph operates as though nothing happened.
3d. If you edit something in the graph editor, the original code pops back.
3e. If you edit something in the text editor instead, you are in big trouble with mismatched visions of the world between the backend and the editor.

**Comment by pmlodawski** [comment]
Possible duplicate #1013

**Comment by mikusp** [comment]
I'm not able to reproduce that on master@https://github.com/luna/luna-studio/commit/4d5d8f55bc5765c9fc5bf941d41d9653ab3fa5b2

**Comment by piotrMocz** [comment]
I'm not able to reproduce it either. Same commit, MacOS High Sierra (10.13).
