### ISSUE TITLE
No connections for list literals

### ISSUE THREAD

**Issue by kustosz** [luna/luna-studio#1017]
Create a node `number1 = 2` and then `list1 = [number1]`. We're expecting a connection here, but there's none:
<img width="437" alt="screen shot 2018-07-30 at 20 05 03" src="https://user-images.githubusercontent.com/1214109/43414751-01b8ecb0-9434-11e8-99c0-62f930fb97a9.png">

**Comment by ljkania** [comment]
PR is merged. Is this issue still open?

**Comment by piotrMocz** [comment]
Works like a charm (see the screenshot).

<img width="301" alt="screen shot 2018-09-24 at 18 17 31" src="https://user-images.githubusercontent.com/3109645/45964449-1f3a3a00-c026-11e8-98f7-f6b88d14b3f3.png">

Closing the issue.
