### ISSUE TITLE
Function created in the node editor is unnecessarily assigned to a variable

### ISSUE THREAD

**Issue by piotrMocz** [luna/luna-studio#1031]
Repro:
1. In the graph editor, hit `Tab` to bring up the searcher.
2. Type an arbitrary function, like: `def foo x: x + 1`.
3. There you go, the generated code looks like this:
```
expr1 = def foo x: x + 1
```
Which then doesn't let you use `foo 15`, as the name `foo` is undefined.

**Comment by mikusp** [comment]
Cannot reproduce on 1.4 on my machine

**Comment by piotrMocz** [comment]
That's true, on 1.4 I cannot reproduce it either. It happened on my dev head (basegl branches). I will confirm that it still is a problem.
