### ISSUE TITLE
Bundling Dataframes in new project

### ISSUE THREAD

**Issue by mikusp** [luna/luna-studio#1058]
### Summary

Bundling Dataframes with every new project.

### Value

Users can use Dataframes right out of the box

### Specification

Ad-hoc plan: Dataframes is bundled with luna-studio package, is extracted to .luna or somewhere else, on createProject luna-empire copies Dataframes to /new/project/path/local_libs.
That should provide the functionality with minimal changes to out structure. Pros: no changes to installer, Dataframes version will be updated with new Luna Studio version released. Cons: need for copying Dataframes on each project creation.

Questions: what about Python bundling?

### Acceptance Criteria & Test Cases

After this task is done, new project created should have Dataframes imported and all functionality working.

**Comment by piotrMocz** [comment]
We won't be doing it this way. Thanks to @mikusp 's changes, Luna Studio will now see every project located next to `Std` and that's where we'll be downloading any external packages (e.g. the Dataframes).

Closing in favour of https://github.com/luna/luna-manager/issues/211.
