### ISSUE TITLE
Adding a node on a top-level on the left side of the other nodes miss new line sign in text representation

### ISSUE THREAD

**Issue by sylwiabr** [luna/luna-studio#1064]
### General Summary

If the node will be added on a top-level on the left side of existing nodes, the code which will append will end with the new function end in the same line where next definition started. It is working properly with new unsaved project but behaves wrongly for our examples like `TramsPlayground`
### Steps to Reproduce

Please list the reproduction steps for your bug. For example:

1. Open `TramsPlayground`
2. Go to top-level by double-clicking in node editor background
3. Add node `def bar` on the left side of existing nodes

### Expected Result

```
import Std.Base
import Std.HTTP
import Std.Geo
import Std.Time

«24»def bar:
    None

«25»def getVehicles:
    «0»response = Http . getJSON "http://www.ttss.krakow.pl/internetservice/geoserviceDispatcher/services/vehicleinfo/vehicles"
    «1»vehicles = response . getList "vehicles"
    «2»validVehicles = vehicles . filter (_ . lookup "longitude" . isJust)
    validVehicles

«21»def formatVehicle a:### META {"metas":[{"marker":0,"meta":{"_displayResult":true,"_selectedVisualizer":["base: json","/Users/marcinkostrzewa/code/luna-studio/luna-studio/atom/lib/visualizers/base/json/json.html"],"_position":{"fromPosition":{"_vector2_y":-192,"_vector2_x":0}}}},{"marker":1,"meta":{"_displayResult":false,"_selectedVisualizer":["base: json","/Users/marcinkostrzewa/code/luna-studio/luna-studio/atom/lib/visualizers/base/json/json.html"],"_position":{"fromPosition":{"_vector2_y":-192,"_vector2_x":288}}}},{"marker":2,"meta":{"_displayResult":true,"_selectedVisualizer":["base: json","/Users/marcinkostrzewa/code/luna-studio/luna-studio/atom/lib/visualizers/base/json/json.html"],"_position":{"fromPosition":{"_vector2_y":-192,"_vector2_x":560}}}}]}
```

### Actual Result

<img width="609" alt="zrzut ekranu 2018-08-30 o 16 33 21" src="https://user-images.githubusercontent.com/12892578/44858530-7f7dcc00-ac72-11e8-86f8-db572fd128c0.png">

### Luna Version

- luna-studio with luna bumped:` 57f055779900be97ad6af00f5c033a030295ec56`

**Comment by mikusp** [comment]
Cannot reproduce on 1.5 on Linux

**Comment by sylwiabr** [comment]
Works for me too
