### ISSUE TITLE
macOS - Signing In by Certificate

### ISSUE THREAD

**Issue by lgawlik** [luna/luna-studio#1068]
### Summary
Currently during installation on Mac, there is a warring about "untrusted developer". We need to remove the warning. 

### Value

Installation on Mac will be without warning, it will be smooth

### Specification

- Certificate type is "Developer ID Application"
- Certificate get be generated using XCode, and our company development account (Lukasz Gawlik knows details of company account to use)

Open questions:
- To be clarified what should be signed in, Luna installer, Luna Studio, ..., (all installed applications)? 
- To be clarified if file attributes like application name, version etc should be provided/corrected)

### Acceptance Criteria & Test Cases

- During installation there is not a warning about "untrusted developer"

**Comment by piotrMocz** [comment]
https://s3-us-west-2.amazonaws.com/packages-luna/darwin/lunaInstaller-darwin-signed.zip please verify if this installs without problems -- on my machine it does, but we need a bigger test population.

**Comment by piotrMocz** [comment]
This task is done, as the installer is signed and doesn't issue any warnings. However, it's not automated. Automation is tracked here: https://github.com/luna/deploy/issues/25
