### ISSUE TITLE
Reconsider the default distances between nodes

### ISSUE THREAD

**Issue by sylwiabr** [luna/luna-studio#1069]
Received feedback:

The default distances between nodes are something to think through. Right now every time I add a node, it ends up on top of my visualisations and I need to drag it. And it's really easy to disconnect a node while dragging (or connect it to sth else).

**Comment by wdanilo** [comment]
It's because the current visualizations are scaling when moving the camera. I consider this a serious bug but changing node distances is a wrong solution to it because it makes the language much less concise and just worse than code. The new GUI aims to solve this issue.
