### ISSUE TITLE
Simplify the algorithm for sliders in expanded nodes 

### ISSUE THREAD

**Issue by sylwiabr** [luna/luna-studio#1071]
### Summary

Now the algorithm responsible for calculating sliders value is very complicated and it is easy to get enormous value. We should make it simple and linear.
### Value

The sliders in expanded nodes will be usable 

### Specification

- The formula which calculate the value for the slider use parameters like how fast the mouse position change. It should be simple and linear dependency instead.

### Acceptance Criteria & Test Cases

- Create the node with the list of the Int values, create another node with `take` function, be able to set and change the number of Ints you are taking from previous list.

**Comment by piotrMocz** [comment]
It does work, but in an interesting way.
1. I create the list: `list1 = [1,2,3,4,5,6,7,8,9,10]`
2. I create the `take` node: `take1 = list1 . take 5`
3. I expand the node and start playing with the slider: it works well but I can very easily reach values larger than the list's size (but that's okay and just gives you the whole list). However, I can equally easily reach negative values and here an interesting thing happens:
    a) say I chose `-5` as the value of the slider.
    b) it gets converted to `5`
    c) I get the whole list as a result! (so there's a discrepancy between what's on the node and what actually got calculated.

I feel that this task is done but a new one emerged ;)
