### ISSUE TITLE
Request timing issue in text editor

### ISSUE THREAD

**Issue by mikusp** [luna/luna-studio#1073]
I suspect that we have some kind of request timing/ordering issue now in text editor. Because we are waiting a number of ms before sending substitute request, another request might be sent before, effectively invalidating substitute contents.

Could you try to confirm my findings? How did I encounter that:
1. Copy some code
2. Type something into code, e.g. type Enter on the end of a line
3. Immediately after, hit ctrl-v
4. In logs, I see that paste request was processed before substitute request, resulting in a silent corruption of code in backend.

If what I suspect is true, maybe we should send any pending substitute requests before sending a new request? I leave that to you though.

**Comment by piotrMocz** [comment]
The issue doesn't seem to exist anymore: I repeated the steps and the `substitute` request was processed **before** the `paste` request, which, if I understand correctly, is the desired behaviour. @mikusp you can confirm or deny ;)

I'm accepting the task and closing.
