### ISSUE TITLE
Searcher recommendation are not always valid

### ISSUE THREAD

**Issue by sylwiabr** [luna/luna-studio#1078]
### General Summary

- Read a csv file and try to make a chart: searcher is not recommending exact match, if you write the full method name no imports will be added
![zrzut ekranu z 2018-09-18 15-01-04](https://user-images.githubusercontent.com/12892578/45689595-b3069480-bb54-11e8-8ff0-d58a73cb3d46.png)

### Steps to Reproduce

Please list the reproduction steps for your bug. For example:

1. Read csv file
2. press Tab and start typing `chart` in node editor

### Expected Result

- Searcher should recommend exact match instead of `character` method from `Text` class

### Actual Result
Actual result visible on print screen

**Comment by ljkania** [comment]
@sylwiabr: can you confirm that this issue is resolved?

**Comment by sylwiabr** [comment]
looks fine
