### ISSUE TITLE
Imports not updated in gui when it requests to add imports

### ISSUE THREAD

**Issue by ljkania** [luna/luna-studio#1086]
Backend incorrectly responses to `AddImport` request which results in not updated searcher hints (already imported module functions/methods are not scored correctly) until next `GetProgram` request.

### General Summary

- Imports known by gui are inconsistent with imports in backend.

### Steps to Reproduce

1. Create `WebSocketInstance` using searcher (use hint from searcher)
2. `Std.HTTP` import should be added in code
3. Hints from `Std.HTTP` are never first choice of searcher (try `stream`)
4. Save file
5. Restart
6. Imports are updated and hints works correctly.

### Expected Result

- Hints from `Std.HTTP` are treated as imported as soon as import is added

### Actual Result

- It happens not earlier than another `GetProgram` request (after crash/restart/changing bc)

### Luna Version

- 1.4

**Comment by piotrMocz** [comment]
I feel like this was fixed by: https://github.com/luna/luna-studio/issues/1075
Anyways, it does work, good job ;)
Although the searcher still doesn't see the locally defined functions: https://github.com/luna/luna-studio/issues/1105
