### ISSUE TITLE
Breaking line breaks the project

### ISSUE THREAD

**Issue by ljkania** [luna/luna-studio#1087]
### General Summary

Breaking lines was never supported but now we are unable to revert broken state by using undo.

### Steps to Reproduce

1. Make some line in luna-studio and break it into two lines (I did it before `.`)
2. Graph is displaying some errors
3. Press ctrl-z

### Expected Result

- Change is reverted and graph is in state before 1.

### Actual Result

- Graph is still broken but in different way.

### Luna Version

- 1.41016

**Comment by sylwiabr** [comment]
Actually I have one more thing: sometimes breaking the line is making the markers visible in node expression
<img width="549" alt="zrzut ekranu 2018-10-23 o 15 36 26" src="https://user-images.githubusercontent.com/12892578/47364497-bce26100-d6d9-11e8-9c18-2b5cf4ce7688.png">

write the code:
```
import Std.Base

def main:
    n = 2
    foo = n.+ 3
    None```
set coursor before `.+` , press enter and then tab
