### ISSUE TITLE
New way to store METADATA while not interfering with the code

### ISSUE THREAD

**Issue by TheOnlyArtz** [luna/luna-studio#1092]
Luna Studio 1.4

### General Summary

Basically the way Luna stores meta data right now is within the actual code the developer is writing.
What if the developer is willing to share their code with other developers? they will encounter lots of markers and basically "metadata" in their code, which can get very messy and confusing.
What if we could store metadata in separate files? for example let's say I got this code:

```elm
import Std.Base

def main:
    test = "Test me!"
```

But this code is being stored as 
```elm
import Std.Base

«0»def main:
    «1»test = "Test me!"

### META {"metas":[{"marker":1,"meta":{"_displayResult":false,"_selectedVisualizer":["LunaVisualizer: base: json","base\\json\\json.html"],"_position":{"fromPosition":{"_vector2_y":0,"_vector2_x":0}}}}]}
```
It **includes** the metadata and interferes with the actual code
What about having the developer to write their code but when they save the file the metadata will be stored in an external file? like this
`MyProject/Metadata/Directory/Main.luna.metadata`:
```elm
«0» = 3:0
«1» = 4:4

### META {"metas":[{"marker":1,"meta":{"_displayResult":false,"_selectedVisualizer":["LunaVisualizer: base: json","base\\json\\json.html"],"_position":{"fromPosition":{"_vector2_y":0,"_vector2_x":0}}}}]}
```

This way the IDE will be able to get meta data from the wanted code without interfering with the actual code. `<<x>>` resembles the marker id while the format is `line:column` so the IDE will know exactly where to look at!
### Motivation
I've opened a repo on GitHub as my first project with Luna, and I found it really annoying that I got those markers in my code, but think about it in that way, every time people that use Luna will want to share their code they will deal with the exact same issue.

**Comment by PurgePJ** [comment]
I would vote for having 2 different files, if you want to export without metadata, of course:

`hello.luna` would be the "clean format".
`hello.lunam` would be `hello`'s metadata.

**Comment by iamrecursion** [comment]
Superseded by design efforts for the IDE protocol, which will manage the node metadata internally.
