### ISSUE TITLE
Creating empty function on nodes fail

### ISSUE THREAD

**Issue by wdanilo** [luna/luna-studio#1093]
### General Summary

I'm trying to create a function in `main` using node editor. It's a critical bug because it makes creating functions impossible.

### Steps to Reproduce

1. Open new project
2. Tab -> `def foo`. Here is the first bug - it should already create an empty function, not raise an error.
3. Rename `def foo` to `def foo:` 
4. Double click on the node
5. Tab -> `None` and connect it to output. Here is another error - every expression we've created is in `main`, not in `foo`.
6. Using text editor we indent the expressions so we've got:

```haskell
def main:
    def foo:
        none1 = None
        none1
    test = "Test me!"
```
And here is another error - after entering `foo` node we see 2 non connected nodes. No connection means there is no logical connection of the entities and here is the same variable and they need to be connected.

### Expected Result

Every step above should behave as described. In particular, creating node `def foo` should create a new empty function. Entering it and creating nodes should create indented code. Manually indenting lines should work as well.

### Luna Version

1.4

**Comment by TheOnlyArtz** [comment]
You might want to merge this issue with [#1070](https://github.com/luna/luna-studio/issues/1070)

**Comment by piotrMocz** [comment]
It works very nicely!

The created function (equivalent to step 2 from above) is well-formatted both in text rep and when double-clickind the node's expression. I wasn't able to get it to crash after playing with the body of the function.

Well done!
