### ISSUE TITLE
Copy of text should by default not include markers

### ISSUE THREAD

**Issue by wdanilo** [luna/luna-studio#1094]
### General Summary

Including markers in copied text by default is error prone and people don't know why it's happening. It prevents users from telling about errors and sharing code. We should allow copyinig text with markers using something like `ctrl + shift + c`, while `ctrl + c` should copy only unmarked code.

It's critical cause it prevents users from sharing code.

### Steps to Reproduce

Please list the reproduction steps for your bug. For example:

1. Select text, click `ctrl + c`
2. Paste it in another aplication. Markers are seen.

### Expected Result

No markers should be seen.

### Luna Version
1.4

**Comment by mikusp** [comment]
Already done in newer versions

**Comment by TheOnlyArtz** [comment]
> Already done in newer versions

Thank you so much, was waiting for it for sometime !

**Comment by mikusp** [comment]
1.5 is released now
