### ISSUE TITLE
Missing connection to section field

### ISSUE THREAD

**Issue by wdanilo** [luna/luna-studio#1096]
### General Summary

Write the following code using text editor:

```haskell
import Std.Base

def main:
    foo = 1 
    foo +
```

The result is:

![9](https://user-images.githubusercontent.com/1623053/45886763-37a61c80-bdba-11e8-8674-c55b57175086.png)

It's critical cause it's very simple expression and the results are totally misleading.

### Expected Result

- The nodes refer to the same variable and should be connected.

### Luna Version

1.4

**Comment by piotrMocz** [comment]
Works like a charm ;)
