### ISSUE TITLE
Backspace breaks nodes

### ISSUE THREAD

**Issue by wdanilo** [luna/luna-studio#1098]
### General Summary

Backspace in text editor works really strange sometimes. It's critical cause such operation is **very** common.

### Steps to Reproduce

1. Open new scene
2. Remove body of main and write instead (don't make any mistake, just write it):

```haskell
import Std.Base

def main:
    foo = 1 
    foo . bar
```

3. Set cursor after `bar` and press backspace unless you've got in line only `foo` left.
4. Write `. bar` again, so you get the same code as earlier. The result:

![9](https://user-images.githubusercontent.com/1623053/45883374-33293600-bdb1-11e8-8a16-329b84f8c4fa.png)

(there is **nothing** more on the stage)

### Expected Result

- Pressing backspace should not break anything.

### Luna Version
1.4

**Comment by piotrMocz** [comment]
This works -- pressing backspace and writing the same thing again produces the same result. Although, I must say that in general the way the graph updates after writing in the text editor is not perfect -- after writing the node's name I need to at least enter a whitespace for the graph editor to catch up (and color the node/display its value). That is, however, known and tracked elsewhere, I believe.
