### ISSUE TITLE
Importing modules below initial Std.Base will result in non exhaustive pattern match error

### ISSUE THREAD

**Issue by TheOnlyArtz** [luna/luna-studio#1101]
### General Summary

This bug basically messes up with the parser and the visualization part in general, as soon as this bug happens, you will have to start a new project in order to work on the code, even deleting the whole file content won't help.

### Steps to Reproduce

Please list the reproduction steps for your bug. For example:

1. Create a new project.
2. import a module **BELOW** `import Std.Base` 
3. Observe

### Expected Result

This error shouldn't raise at all!

### Actual Result
![image](https://user-images.githubusercontent.com/30025874/45916615-a85c4000-be71-11e8-8ef2-e5b946484460.png)

In this picture I tried to delete the file content and start over after reproducing the bag

### Luna Version
Luna studio v1.4.101.6

**Comment by mikusp** [comment]
Thank you for the report. While it's not as severe as you described (you can still work with the file), it will be fixed in the next version.
