### ISSUE TITLE
Copy-pasting whole file throws exception

### ISSUE THREAD

**Issue by wdanilo** [luna/luna-studio#1107]
### Steps to Reproduce

1. Copy the following code:
```haskell
import Std.Base

class Foo:
    x :: Bar

def main:
    foo1 = Foo 3
    x1 = foo1 . x
    test = "Test me!"
    None
```
2. Open new project
3. Select the whole code
4. Press `ctrl + v`

### Expected Result

It should work

### Actual Result

![9](https://user-images.githubusercontent.com/1623053/45922522-2817f800-bece-11e8-913c-0600c018ab3b.png)

### Luna Version
1.4.101.6

**Comment by piotrMocz** [comment]
Okay, works nicely ;)
