### ISSUE TITLE
ToJSON instances are not automatically derived

### ISSUE THREAD

**Issue by wdanilo** [luna/luna-studio#1113]
### General Summary

It's very cumbersome to write every `toJSON` instance by hand. Thus our datatypes should provide a way to derive it. There are 2 approaches. First is to provide deriving mechanism (like in Haskell). Second is to allow some methods to default to a generic implementation. While both ways require some complex changes to the compiler, we should for now just automatically derive `toJSON` for every class if not provided with an explicit implementation. JSON is our basic visualization type and having such functionality would make debugging graphs much easier.

### Steps to Reproduce

Use the code:

```haskell

import Std.Base

class Vector:
    x :: Int
    y :: Int
    z :: Int

def main:
    v = Vector 1 2 3 

```

Another example. I was playing with time library and I've created a code:

```haskell
import Std.Time
import Std.Graphics2D
import Std.Base


def main:
    circle1 = circle 12.0
    now1 = Time.now
    timeZone1 = now1 . timeZone
    None
```

There is **no way** to easily inspect what `timeZone1` is. You cannot print it, nor visualize it. Thus exploration of Luna and learning it is very, very hard.

### Expected Result

The `v` node should have working visualization.

### Actual Result

The visualization is not available due to lack of `toJSON` method implementation.

### Luna Version
1.4.101.6

**Comment by piotrMocz** [comment]
That's done and works really nice, awesome work.
