### ISSUE TITLE
Lack of documentation and examples to standard libraries

### ISSUE THREAD

**Issue by wdanilo** [luna/luna-studio#1118]
### General Summary

It is simply impossible to use standard libraries due to lack of documentation. However, even writing documentation to every function is not enough. When exploring a module, like `Http`, we need to have in documentation a link / snippet with an example. It needs to be available in **every** function documentation. Alternatively we should provide information which function is the most important so users could explore looking at the right function. The former solution is better and more user friendly.

### Steps to Reproduce

1. Open node searcher
2. Try to connect to HTTP service

### Expected Result

The node searcher should be the center of information.

### Actual Result

The documentation is missing in 90% of functions. Moreover, even if it's there, there are no examples / snippets / links to example projects. Even if they are somewhere, I could not find them, so exploring them is too hard.

### Luna Version
1.4.101.6

**Comment by sylwiabr** [comment]
fixed by https://github.com/luna/luna/pull/391
