### ISSUE TITLE
Code cut does not work

### ISSUE THREAD

**Issue by wdanilo** [luna/luna-studio#1121]
### Steps to Reproduce

1. Start with the code:

```haskell
import Std.Base

def main:
    test = "Test me!"
    None

def test:
    5
```

2. Select the `test` function
3. Press `ctrl + x`

### Expected Result

The code should be cut and we should be able to paste it.

### Actual Result

The code disappears and we are able to paste a blank line.

### Luna Version

1.4.101.6

**Comment by mikusp** [comment]
@pmlodawski @ljkania can you tell if we handle cut ourselves or was this overlooked and Atom handles it itself?

**Comment by ljkania** [comment]
This is duplicate of [this issue](https://github.com/luna/luna-studio/issues/1091).
I don't have an answer right away, @pmlodawski do you have one or we need to investigate?

**Comment by mikusp** [comment]
Duplicate of #1091
