### ISSUE TITLE
No error on duplicate function definition

### ISSUE THREAD

**Issue by wdanilo** [luna/luna-studio#1122]
It's a serious bug, cause it could happen easily and it is very dangerous. Luna discards earlier function definitions and overrides them with later ones.

### Steps to Reproduce

1. Consider the code:

```haskell
import Std.Base

def test:
    5

def test: 
    6

def main:
    foo = test
    None
```

### Expected Result

There should be an error about duplicate function definition (unless we've got overloading).

### Actual Result

We've got nodes named the same and Luna uses the later definition silently.

### Luna Version
1.4.101.6

**Comment by piotrMocz** [comment]
@mikusp next time please at least leave a note that this requires bumping the Luna version (or, even better, bump the version -- bumping is not part of the testing :D)

**Comment by piotrMocz** [comment]
Noice!

@mikusp food for thought: we're reporting the errors on use-site. That's quite unfortunate, given that I can happily define a 100 classes with lots of duplication and I won't be notified until I try to use one of them.

Also, the following behaviour is quite misleading:
1. I create a class, like this:
```python
class Foo:
    x :: Int
    x :: Int
```
2. I create an instance of this class:
```python
obj = Foo 10 20
```
3. There is no error, which gives me the false sense of security that my code is alright.
4. The ports of the node suffer from the issue that's already reported, by the way: https://github.com/luna/luna-studio/issues/1142

See this issue for further discussion: https://github.com/luna/luna-studio/issues/1153
