### ISSUE TITLE
Type checker does not refresh after changes to code

### ISSUE THREAD

**Issue by wdanilo** [luna/luna-studio#1124]
### Steps to Reproduce

1. Start with this wrong code and navigate inside the node `foo`:

```haskell
import Std.Base

def main:    
    def foo: number1 = 12
             number2 = 19
             None
    None
```

2. Reformat the code to:

```haskell
import Std.Base

def main:    
    def foo: 
        number1 = 12
        number2 = 19
        None
    None

```

### Expected Result

It should start working.

### Actual Result

Unless I get out and get in into the node I see:

![9](https://user-images.githubusercontent.com/1623053/45936530-13179380-bfb8-11e8-9acb-062c30fe3936.png)

### Luna Version
1.4.101.6

**Comment by pmlodawski** [comment]
Tested it and it works now
