### ISSUE TITLE
Maybe values are incorrectly visualized

### ISSUE THREAD

**Issue by wdanilo** [luna/luna-studio#1125]
### Steps to Reproduce

1. Use the code:

```haskell
import Std.Base
def main:
    lst = [1,2,3,4,5,6,7]
    lst' = lst.each x: 
        if x < 5 then Just 1 else Nothing
    None
```

2. See the visualization of `lst'`

### Expected Result

The visualization should show the values - 4 times `Just 1` and 3 times `Nothing`

### Actual Result

```
Array[7]
 0:1
 1:1
 2:1
 3:1
 4:null
 5:null
 6:null
```

It's very contr intuitive and error prone.

### Luna Version
1.4.101.6

**Comment by kustosz** [comment]
You can select different visualization types. This is the bare json viewer. `Maybe` is best represented in json as nulls, the natural encoding. We can create a different visualizer with "pretty printing", this is just json.

**Comment by wdanilo** [comment]
Oh ok, got it!
