### ISSUE TITLE
Node searcher does not display methods when pressing tab with selected node

### ISSUE THREAD

**Issue by wdanilo** [luna/luna-studio#1128]
### Steps to reproduce

This one is important. It prevents users from learning Luna.
Please list the reproduction steps for your bug. For example:

1. Create a node `Time . now`
2. Select it
3. Press tab

### Expected Result

Node searcher should display methods of time for easy exploration

### Actual Result

We see a ton of other, not related functions

### Luna Version
1.4.101.6

**Comment by wdanilo** [comment]
Ok, it's critical. You simply cannot learn Luna without it.

**Comment by ljkania** [comment]
<img width="626" alt="screen shot 2018-11-13 at 16 31 39" src="https://user-images.githubusercontent.com/7061422/48423815-a2902600-e761-11e8-9016-6fd4e92ac639.png">
Works fine for me

**Comment by sylwiabr** [comment]
This is working on current master as @ljkania show.
