### ISSUE TITLE
Working with node graph completely messes the text

### ISSUE THREAD

**Issue by wdanilo** [luna/luna-studio#1132]
### Steps to Reproduce

1. New project
2. top level -> tab -> `def foo`
3. get inside -> tab -> `15`
4. navigate to main and remove the hello wrold node 

### Expected Result

Main should be empty

### Actual Result

The code we get:

```haskell
import Std.Base

def foo:
    number1 = 15
    None

def  me!"
    None

```

### Luna Version
1.4.101.6

**Comment by mikusp** [comment]
It's the same issue as in #1131, closing as duplicate.
