### ISSUE TITLE
Show arguments names on expanded nodes

### ISSUE THREAD

**Issue by sylwiabr** [luna/luna-studio#1138]
### General Summary

When we are working on expanded nodes we can see our arguments as `arg0`, `arg1` etc. We want to know what we have to connect/set as an argument so arguments names instead will be useful.

### Motivation

Easy use of nodes with missing arguments/expanded nodes

**Comment by piotrMocz** [comment]
This works only in one case that I'm aware of: fully applied, user-defined, top-level function, all entered as a single expression over the node.

## Cases that break:

### User-defined top-level function

#### Unapplied function
1. Start with an empty project.
2. Definine a function in the text representation, for example:
```python
def foo x y:
    x + y
```
3. Create, in the graph editor, a node with just this function (unapplied):
    3.1. Hit "Tab" and write `foo`.
    3.2. Hit "Enter" to accept the expression.
    3.3. Hit "Enter" once again to expand the node -- you'll see that the arguments are named `arg0` and `arg1` and not `x` and `y`.

#### Connecting a node in place of an argument of a fully applied function

1. Repeat steps 1 and 2 from above
2. Create a fully applied function:
    2.1. Hit "Tab" and write `foo 12 34`
    2.2. Hit "Enter"
    2.3. Expand the node by hitting "Enter" (you'll notice that the argument names are displayed correctly).
3. Create a node with just a number (hit "Tab", enter `123` and hit "Enter").
4. Click and drag the number node's border to connect it to one of the ports of the function node.
5. Notice how the argument names changed to `arg0` and `arg1`.

#### Modifying a fully applied function using the expanded node controls

1. Repeat all of the steps 1 and 2 from above.
2. In the expanded node, move one of the sliders to change the value.
3. Notice how the argument names switch to `arg0` and `arg1`.

### Functions from the Standard Library

#### Partially applied

1. Hit "Tab" and select one of the top-level functions from the standard library (not methods). For example, we could use `readFile`, which has one argument: `f`.
2. Hit "Enter" to select it without any arguments.
3. Hit "Enter" once again to expand the node: the argument name is `arg0`.

#### Fully applied

Same as above, but enter an argument to the function (a path to any file on your disk).
<img width="251" alt="screen shot 2018-09-28 at 12 43 31" src="https://user-images.githubusercontent.com/3109645/46204064-2611c700-c31c-11e8-9767-f5f9d50d8f66.png">

@mikusp if I'm somehow using this wrong, please correct me. If not, please move the task to the "In Progress" column.

**Comment by piotrMocz** [comment]
First of all: great work, all of the above cases work.

What doesn't work is the names of method arguments (as opposed to function arguments), see this picture:
<img width="946" alt="screen shot 2018-10-02 at 16 36 21" src="https://user-images.githubusercontent.com/3109645/46356363-e3752500-c662-11e8-92ae-897cf884696d.png">

Also, notice how when I change the value with a slider, the names blink, turning to `arg0`, `arg1` for a moment, and then get back to normal. [See the video.](https://drive.google.com/file/d/1p386Zxa4vlz1eelqo8tYJwxr8efNsu1c/view?usp=sharing)

**Comment by mikusp** [comment]
This case is a bit harder than others. In case of methods, they are not resolved to concrete implementation during typechecking. Lookup of method to run is done by interpreter looking at the object at runtime. Before interpreting, we can't resolve method called to Function term and without that, we don't have access to arguments names.

**Comment by iamrecursion** [comment]
This does make me think that the new runtime should be able to do static dispatch on methods where possible.
