### ISSUE TITLE
Unable to connect two inputs to a binary operator.

### ISSUE THREAD

**Issue by piotrMocz** [luna/luna-studio#1142]
This happens on a 1.4.101.7 package on Mac OS.

### General Summary

Cannot connect

### Steps to Reproduce

1. Start with an empty project.
2. Hit "Tab" and create another node with a string, say: "Test me!!"
3. Click the space to the right of the two nodes, hit "Tab" and type `==`.
4. Try to connect one of the text nodes to one of the inputs of the `==`.
5. First error happens: event though it's connected and the displayed type is correct (`Text -> Bool`), the color of the input port is grey, suggesting something is "no yes" in terms of the typechecking.
6. Try to connect the other text to the remaining port:
7. Another error: the previous connection disappears and we're again left with a `Text -> Bool` node.
(if you connect the second text to the self-port, it works okay, still grey)

<img width="408" alt="screen shot 2018-09-25 at 16 53 10" src="https://user-images.githubusercontent.com/3109645/46022777-836f0380-c0e3-11e8-9e17-8c4d4524045a.png">

Note that the resulting code uses the `==` as an infix operator and not a method -- maybe that's why it works like this.

<img width="269" alt="screen shot 2018-09-25 at 16 53 59" src="https://user-images.githubusercontent.com/3109645/46022820-a0a3d200-c0e3-11e8-894c-97e4c8712513.png">

**Comment by mikusp** [comment]
I cannot reproduce this bug on current master

**Comment by wdanilo** [comment]
@piotrMocz please close this bug after you'll test it in some released package (I assume 1.6?)

**Comment by piotrMocz** [comment]
This is a funny one, so here's a better repro:

1. Start by creating a function, on the top-level, say:
```python
def foo x y:
    100
```
2. Create an arbitrary value-node, like: `x = 1`
3. Create a second node, `y = 2`
4. Create a node with the unapplied `foo`
5. Connect the `x` node to the `foo` node
6. Connect the `y` node to the `foo` node and watch the previous connection disappear.
(btw. if you flip the order you may get the right result, but the coloring is still off).

Note: this has to do with not sending an update while connecting or something similar. Here's how to **fix** this bug:
5.1. After connecting the first node, go to top-level and back. The coloring will be fine and the second node will connect fine, producing the right result. The coloring will still be off after the two connections, though.

[Here's a quick video presenting the first scenario, and immediately after the second (fixed) one.](https://drive.google.com/file/d/1bhNd0HmVhxL7YVLSI4Gi8L9MekOBd484/view?usp=sharing)

**Comment by piotrMocz** [comment]
However, given that the repro conditions are more complex than I initially thought, I'm re-labelling this to `Hard` (instead of `Critical`).

**Comment by wdanilo** [comment]
@piotrMocz so the original reported scenario works well?

**Comment by piotrMocz** [comment]
Cannot reproduce this anymore -- this may have gotten fixed by some other bugfix.
