### ISSUE TITLE
Pasting nodes deletes them from node editor

### ISSUE THREAD

**Issue by sylwiabr** [luna/luna-studio#1149]
Please ensure that you are running the latest version of Luna Studio before reporting the bug! It may have been fixed since.

### General Summary

https://drive.google.com/open?id=1_mMSWoqnsoC-5-vdhAF_u1a0boCEEUux

### Steps to Reproduce

Please list the reproduction steps for your bug. For example:

1. Create a new project.
2. Add few nodes.
3. Select part of them.
4. press ctrl+c
5. click on background
6. press ctrl+v

### Expected Result

- nodes identical as selected will be pasted
### Actual Result

-Selected nodes disappear.

### Luna Version

- 1.5

**Comment by piotrMocz** [comment]
I can confirm that this is indeed broken on the current master (https://github.com/luna/luna-studio/commit/a37a78237c62caae83e69e1cd754ab566bc8b8a3).

What happens for me is the code gets pasted with wrong indentation:
<img width="517" alt="screen shot 2018-10-09 at 09 59 57" src="https://user-images.githubusercontent.com/3109645/46654879-3a6e8300-cbaa-11e8-87a2-70db4bfa8266.png">

**Comment by sylwiabr** [comment]
copy-paste is not perfect but it doesn't happen anymore
