### ISSUE TITLE
A node created with the text editor is initially gray.

### ISSUE THREAD

**Issue by piotrMocz** [luna/luna-studio#1158]
When creating a node using the text editor, the node is grey at first. Only when I force an update (e.g. by adding a blank line) it gains the right color.

### Steps to reproduce

1. Open a blank project and delete the contents of the `main` function.
2. Write `foo = 1`
3. Notice that the node is grey but has a value.
4. Add a line break after `foo = 1` -- the node gains color.

@mikusp feel free to reassign this task if you can think of anyone better suited ;)

**Comment by mikusp** [comment]
I can't reproduce that on master

**Comment by mikusp** [comment]
We can't reproduce that now.
