### ISSUE TITLE
NodeDoesNotExist exception when removing a node referenced by another node

### ISSUE THREAD

**Issue by piotrMocz** [luna/luna-studio#1159]
### Steps to reproduce

1. Remove all the lines of the `main` function.
2. Write this:
```python
def main:
    foo = 1
    foo +
```
3. Remove the `foo = 1` line (in the text editor).
4. You will get an exception like this one:
![Screen Shot 2018-10-02 at 16.55.10.png](https://images.zenhubusercontent.com/5967836b61b4ca3b0a74517c/3eb4fc37-8e66-4f6a-ae07-f7bb7ff9790f)

I'd say this way of presenting the exception is not that bad, but the long sequence of hex numbers doesn't tell much and is pretty intimidating.

**Comment by mikusp** [comment]
We can't reproduce that.
