### ISSUE TITLE
Remove warnings in deprecation cop

### ISSUE THREAD

**Issue by pmlodawski** [luna/luna-studio#1167]
### Summary

Remove warnings in deprecation cop

### Value

- User is not confused about yellow wanings of deprecation cop

### Specification

- Resolve all deprecation warnings

### Acceptance Criteria & Test Cases

- Deprecation cop does nor appear

**Comment by piotrMocz** [comment]
@pmlodawski Is there any way to reproduce this issue to see if it disappeared?

**Comment by piotrMocz** [comment]
Ahhh I know now ;) Okay, I can confirm the deprecation cop is gone.
