### ISSUE TITLE
Update button does nothing

### ISSUE THREAD

**Issue by pmlodawski** [luna/luna-studio#1168]
### Summary

- There are reports that "update" button does not work

### Value

- Update button is useful to update Luna Studio

### Specification

- Check what may be problems with update button and fix them

### Acceptance Criteria & Test Cases

- Update button works

**Comment by pmlodawski** [comment]
I'll need your computer to test this. Its working fine on mine

**Comment by sylwiabr** [comment]
Since we are preparing Luna Studio 2.0 without Atom and with new GUI we will not process with this now.
