### ISSUE TITLE
Remove unused luna-studio plugins

### ISSUE THREAD

**Issue by pmlodawski** [luna/luna-studio#1170]
### Summary

- Remove unused luna-studio plugins

### Value

- luna-studio will be more lightweight

### Specification

Remove following plugins:
    busy-signal
    color-picker
    custom-window-title
    git-blame
    git-*
    minimap-codeglance
    minimap-git-diff
    split-diff
    webview
    *haskell*

**Comment by piotrMocz** [comment]
👍  If you are using this locally, remember to remove the `dist/user-config` directory for this to take effect.
