### ISSUE TITLE
Searcher should display functions sorted on usefulness instead of sorting them alphabetically

### ISSUE THREAD

**Issue by ljkania** [luna/luna-studio#1188]
### Summary

Searcher displays hints sorted alphabetically when not connected to any source. We should rather display most common functions.

### Value

- Easier onboarding for new customers.

**Comment by wdanilo** [comment]
@sylwiabr @kustosz @mikusp @mwu-tow Could you list the "best" functions from your libraries users can start with? These need to be rather functions which are not expected to work on instances of some complex, already constructed data types. These are some kind of things users can start their workflow with.

**Comment by lgawlik** [comment]
@sylwiabr @kustosz @mikusp @mwu-tow please provide details described by Wojtek above till Monday 29/10 end of Day. Leszek needs it to finish task.

**Comment by mikusp** [comment]
I have not authored any libraries accessible by users right now, but I can give a couple of pointers:
- from Std.System, `Command.create`
- from Std.Time, `Time.now`
- from Std.WebSocket, `WebSocket.connection`
- from Std.HTTP, `Http.get`, `Http.getJSON`
- from Std.Base probably `readFile`

**Comment by sylwiabr** [comment]
I was already writing it on spectrum:
- HTTP.get and HTTP.getJSON
- JSON.empty
- simple methods like +
- GeoJSONFeature or GeoPoint
- from dataframes Table.fromFile and Table.empty when it will arrive (https://github.com/luna/Dataframes/issues/92)

**Comment by sylwiabr** [comment]
can I test it already?

**Comment by sylwiabr** [comment]
@ljkania ?

**Comment by ljkania** [comment]
You have no way to do it unless there is a list specified. This issue should be silently closed since I've provided a mechanism for that and should be reviewed once this task is done: https://github.com/luna/luna-studio/issues/1276

**Comment by sylwiabr** [comment]
So it should go to blocked column with dependency

**Comment by lgawlik** [comment]
Sorted list (consulted with Sylwia):
- Table.read
- readFile (z Std.Base)
- HTTP.get
- HTTP.getJSON 
- JSON.empty   
- WebSocket.connection
- Time.now
- GeoPoint
- GeoJSONFeature
- Command.create
- +
- -
- %
- *
- /

**Comment by sylwiabr** [comment]
Done with snippets.yaml
