### ISSUE TITLE
[Retrofit] Refactor substitute

### ISSUE THREAD

**Issue by piotrMocz** [luna/luna-studio#1190]

**Comment by wdanilo** [comment]
What is this task about? @piotrMocz please add description

**Comment by piotrMocz** [comment]
@wdanilo this is the task that I retroactively added to fit the PR (ZenHub handles standalone PR-s differently from tasks and if you close the PR it immediately goes to closed which breaks our process).

@ljkania this is tricky to test. AFAICT it is good if it doesn't break anything: well, I wasn't able to find anything that's broken (at least anything I know of: I don't think this causes #1203 or #1202). I will consider this as accepted, unless @mikusp thinks otherwise.
