### ISSUE TITLE
No connection on nested functions

### ISSUE THREAD

**Issue by sylwiabr** [luna/luna-studio#1198]
Please ensure that you are running the latest version of Luna Studio before reporting the bug! It may have been fixed since.

### General Summary

- Please include a high-level description of your bug here.

### Steps to Reproduce

run data frames repository on commit 9c1b1bd

### Expected Result

connection between toList2 and filter2 nodes
### Actual Result

- proper value but no connection

### Luna Version

- Please include the output of `luna-studio --version`.

**Comment by mikusp** [comment]
Please provide some way to reproduce that

**Comment by sylwiabr** [comment]
to reproduce run Dataframes project (https://github.com/luna/Dataframes) on commit 05ee18e5a0b8ecff8a5de0a1505125759e7efbc2

**Comment by sylwiabr** [comment]
Minimal example:
```
def main:
    list1 = [1,2]
    list2 = [1]
    filter3 = list2 . filter (x: x.+ 1 == list1.head.get)
    None
```

**Comment by sylwiabr** [comment]
ctrl+z is not working properly with connections on nested functions:
write a code:
```
def main:
    list2 = [2]
    list1 = [1,2,3,4,5]
    filter1 = list1 . filter (x: x < list2.head.get)
    None
```
disconnect filter1 and list2
press ctrl+z 
result:
`filter1 = list1 . filter list2`
newly created connection will go as a first argument

**Comment by mikusp** [comment]
@sylwiabr should be working on master
