### ISSUE TITLE
Unable to create an inner function in the text representation

### ISSUE THREAD

**Issue by piotrMocz** [luna/luna-studio#1202]
### Steps to reproduce

1. Open a new project
2. Below the `test = "Test me!"` line but above the `None` start typing:
    2.1. `def foo x:` (you'll be seeing different types of `CompileError: SyntaxError [...]` as you type
    2.1. in the next line: `    x + 1` (the error doesn't disappear)
3. When trying to use the function, `foo` is not in scope.

**Comment by pmlodawski** [comment]
Tested it and it works now
