### ISSUE TITLE
Searcher is painfully slow

### ISSUE THREAD

**Issue by wdanilo** [luna/luna-studio#1215]
### General Summary

The Luna Studio Searcher is very slow. When you write a letter you have to wait for it to refresh even 0.5s sometimes and it just looks laggy and breaks the workflow.

### Luna Version

1.5

**Comment by iamrecursion** [comment]
Fixed as of [40e742c](https://github.com/luna/luna-studio/commit/40e742c560921bb94aaaa96a445c53d372509cf9).
