### ISSUE TITLE
"Breadcrumb error" when editing Main.luna

### ISSUE THREAD

**Issue by ricardojmendez** [luna/luna-studio#1329]
Please ensure that you are running the latest version of Luna Studio before reporting the bug! It may have been fixed since.

### General Summary

Got a non-specific "Breadcrumb error" when editing Main.luna on the Technical Analysis project

### Steps to Reproduce

Please list the reproduction steps for your bug. For example:

1. Opened the Technical Analysis project
2. Played around with the UI a bit
3. Edited line 10, changed `number1 = 16` to `number1= 20`.
4. Error window popped up

```
Breadcrumb {_items = [Definition {_nodeId = 2fa7326d-040e-47c7-b913-d5a77a36f205}]}

while processing event

empire.atom.file.substitute.response
Please report this bug on our github
```
### Expected Result

Unclear, I was experimenting to see if editor changes had any effect on the graph.

### Actual Result

Breadcrumb {_items = [Definition {_nodeId = 2fa7326d-040e-47c7-b913-d5a77a36f205}]}

while processing event

empire.atom.file.substitute.response

======= logs: =======

=== luna-empire-stdout---supervisor-h3Uyan.log ===
INFO 2019-02-18T10:00:41.734935Z	:: received empire.graph.node.typecheck
INFO 2019-02-18T10:00:41.735456Z	:: received empire.graph.node.typecheck
INFO 2019-02-18T10:00:41.735938Z	:: received empire.graph.node.typecheck
INFO 2019-02-18T10:00:41.736336Z	:: received empire.graph.node.typecheck
INFO 2019-02-18T10:00:41.736964Z	:: received empire.graph.node.typecheck
INFO 2019-02-18T10:00:41.737339Z	:: received empire.graph.node.typecheck
INFO 2019-02-18T10:00:41.737912Z	:: received empire.graph.node.typecheck
INFO 2019-02-18T10:00:41.738249Z	:: received empire.graph.node.typecheck
INFO 2019-02-18T10:00:41.738901Z	:: received empire.graph.node.typecheck
INFO 2019-02-18T10:00:41.739237Z	:: received empire.graph.node.typecheck
INFO 2019-02-18T10:00:41.739868Z	:: received empire.graph.node.typecheck
INFO 2019-02-18T10:00:42.070475Z	:: received empire.graph.result.update
INFO 2019-02-18T10:00:42.363334Z	:: received empire.graph.result.update
INFO 2019-02-18T10:00:42.709639Z	:: received empire.graph.result.update
INFO 2019-02-18T10:00:42.930509Z	:: received empire.graph.result.update
INFO 2019-02-18T10:00:42.931099Z	:: received empire.graph.result.update
INFO 2019-02-18T10:00:43.088537Z	:: received empire.graph.result.update
INFO 2019-02-18T10:00:43.089374Z	:: received empire.graph.result.update
INFO 2019-02-18T10:00:43.372243Z	:: received empire.graph.result.update
INFO 2019-02-18T10:00:43.749237Z	:: received empire.graph.result.update
INFO 2019-02-18T10:00:44.033689Z	:: received empire.graph.result.update
INFO 2019-02-18T10:00:44.475642Z	:: received empire.graph.result.update
INFO 2019-02-18T10:00:44.525521Z	:: received empire.graph.node.typecheck
INFO 2019-02-18T10:00:44.526216Z	:: received empire.graph.node.typecheck
INFO 2019-02-18T10:00:44.52685Z	:: received empire.graph.node.typecheck
INFO 2019-02-18T10:00:44.527286Z	:: received empire.graph.node.typecheck
INFO 2019-02-18T10:00:44.527823Z	:: received empire.graph.node.typecheck
INFO 2019-02-18T10:00:44.528613Z	:: received empire.graph.node.typecheck
INFO 2019-02-18T10:00:44.529095Z	:: received empire.graph.node.typecheck
INFO 2019-02-18T10:00:44.529727Z	:: received empire.graph.node.typecheck
INFO 2019-02-18T10:00:44.530067Z	:: received empire.graph.node.typecheck
INFO 2019-02-18T10:00:44.530722Z	:: received empire.graph.node.typecheck
INFO 2019-02-18T10:00:44.531205Z	:: received empire.graph.node.typecheck
INFO 2019-02-18T10:00:44.531971Z	:: received empire.graph.node.typecheck
INFO 2019-02-18T10:00:44.532376Z	:: received empire.graph.node.typecheck
INFO 2019-02-18T10:00:44.53305Z	:: received empire.graph.result.update
INFO 2019-02-18T10:00:44.533471Z	:: received empire.graph.result.update
INFO 2019-02-18T10:00:44.534068Z	:: received empire.graph.result.update
INFO 2019-02-18T10:00:44.534554Z	:: received empire.graph.result.update
INFO 2019-02-18T10:00:44.535244Z	:: received empire.graph.result.update
INFO 2019-02-18T10:00:44.815005Z	:: received empire.graph.result.update
INFO 2019-02-18T10:00:45.14725Z	:: received empire.graph.result.update
INFO 2019-02-18T10:00:45.148193Z	:: received empire.graph.result.update
INFO 2019-02-18T10:00:45.315553Z	:: received empire.graph.result.update
INFO 2019-02-18T10:00:45.316022Z	:: received empire.graph.result.update
INFO 2019-02-18T10:00:45.581913Z	:: received empire.graph.result.update
INFO 2019-02-18T10:01:20.677593Z	:: received empire.graph.collaboration.update
INFO 2019-02-18T10:01:23.913181Z	:: received empire.graph.collaboration.update
INFO 2019-02-18T10:01:24.007634Z	:: received empire.graph.collaboration.update
INFO 2019-02-18T10:01:52.700016Z	:: received empire.graph.saveSettings.request
INFO empire.graph.saveSettings.request: Request {_location = GraphLocation {_filePath = "/var/folders/8v/d28f01fd1bb445_1ngwjym600000gn/T/luna4534/tutorials/TechnicalAnalysis/src/Main.luna", _breadcrumb = Breadcrumb {_items = [Definition {_nodeId = 2fa7326d-040e-47c7-b913-d5a77a36f205}]}}, _settings = LocationSettings {_visMap = Just (fromList [(TCons "KDE2" [],("ImportedVisualizer: Dataframes: image: plot","image\\image.html")),(TCons "Heatmap" [],("ImportedVisualizer: Dataframes: image: plot","image\\image.html")),(TCons "KDE" [],("ImportedVisualizer: Dataframes: image: plot","image\\image.html")),(TCons "Plot" [],("ImportedVisualizer: Dataframes: image: plot","image/image.html"))]), _camera = CameraTransformation {_screenToLogical = ┌                                                                             ┐
│ 1.2590317951737182                0.0                0.0                0.0 │
│                0.0 1.2590317951737182                0.0                0.0 │
│                0.0                0.0                1.0                0.0 │
│ 483.30171475216594 112.41911499311595                0.0                1.0 │
└                                                                             ┘, _logicalToScreen = ┌                                                                                 ┐
│  0.7942611170212921                 0.0                 0.0                 0.0 │
│                 0.0  0.7942611170212921                 0.0                 0.0 │
│                 0.0                 0.0                 1.0                 0.0 │
│ -383.86775981736116  -89.29013184897735                 0.0                 1.0 │
└                                                                                 ┘, _lastInverse = 0}}}
INFO 2019-02-18T10:01:52.722535Z	:: sending response for empire.graph.saveSettings.request
INFO 2019-02-18T10:01:52.722535Z	:: ()
INFO 2019-02-18T10:01:52.72452Z	:: received empire.graph.saveSettings.response
INFO 2019-02-18T10:01:55.908744Z	:: received empire.atom.file.substitute.request
INFO empire.atom.file.substitute.request: Request {_location = GraphLocation {_filePath = "/var/folders/8v/d28f01fd1bb445_1ngwjym600000gn/T/luna4534/tutorials/TechnicalAnalysis/src/Main.luna", _breadcrumb = Breadcrumb {_items = [Definition {_nodeId = 2fa7326d-040e-47c7-b913-d5a77a36f205}]}}, _diffs = [TextDiff {_range = Just (Point {_column = 14, _row = 9},Point {_column = 16, _row = 9}), _newText = "", _cursor = Just (Point {_column = 14, _row = 9})}]}
INFO 2019-02-18T10:01:55.998886Z	:: sending response for empire.atom.file.substitute.request
INFO 2019-02-18T10:01:55.998886Z	:: Diff {_reversedModifications = [SetExpression (ModificationSetExpression {_setExpressionNodeLoc = NodeLoc {_path = NodePath {_localBc = Breadcrumb {_items = []}}, _nodeId = b8c9b11b-4afc-4970-a1f4-eca08eed9485}, _newExpression = "(EmptyExpression)"}),SetNodeCode (ModificationSetNodeCode {_setNodeCodeNodeLoc = NodeLoc {_path = NodePath {_localBc = Breadcrumb {_items = []}}, _nodeId = b8c9b11b-4afc-4970-a1f4-eca08eed9485}, _newNodeCode = ""}),SetInPorts (ModificationSetInPorts {_setInPortsNodeLoc = NodeLoc {_path = NodePath {_localBc = Breadcrumb {_items = []}}, _nodeId = b8c9b11b-4afc-4970-a1f4-eca08eed9485}, _newInPortTree = LabeledTree {_subtrees = InPorts {_self = Nothing, _head = Nothing, _args = []}, _value = Port {_portId = [], _name = "alias", _valueType = TStar, _state = WithDefault (Expression "(EmptyExpression)")}}})]}
INFO 2019-02-18T10:01:56.008233Z	:: received empire.atom.file.substitute.update
INFO 2019-02-18T10:01:56.009644Z	:: received empire.atom.file.substitute.response
INFO 2019-02-18T10:01:56.041504Z	:: received empire.graph.node.typecheck
INFO 2019-02-18T10:01:56.042488Z	:: received empire.graph.node.typecheck
INFO 2019-02-18T10:01:56.042969Z	:: received empire.graph.node.typecheck
INFO 2019-02-18T10:01:56.043429Z	:: received empire.graph.node.typecheck
INFO 2019-02-18T10:01:56.043947Z	:: received empire.graph.node.typecheck
INFO 2019-02-18T10:01:56.044453Z	:: received empire.graph.node.typecheck
INFO 2019-02-18T10:01:56.045299Z	:: received empire.graph.node.typecheck
INFO 2019-02-18T10:01:56.045821Z	:: received empire.graph.node.typecheck
INFO 2019-02-18T10:01:56.046711Z	:: received empire.graph.node.typecheck
INFO 2019-02-18T10:01:56.047115Z	:: received empire.graph.node.typecheck
INFO 2019-02-18T10:01:56.047794Z	:: received empire.graph.node.typecheck
INFO 2019-02-18T10:01:56.048129Z	:: received empire.graph.node.typecheck
INFO 2019-02-18T10:01:56.048751Z	:: received empire.graph.node.typecheck
INFO 2019-02-18T10:01:56.049161Z	:: received empire.graph.result.update
INFO 2019-02-18T10:01:56.04976Z	:: received empire.graph.result.update
INFO 2019-02-18T10:01:56.050106Z	:: received empire.graph.result.update
INFO 2019-02-18T10:01:56.050788Z	:: received empire.graph.result.update
INFO 2019-02-18T10:01:56.051127Z	:: received empire.graph.result.update
INFO 2019-02-18T10:01:56.051722Z	:: received empire.graph.result.update
INFO 2019-02-18T10:01:56.05212Z	:: received empire.graph.result.update
INFO 2019-02-18T10:01:56.052774Z	:: received empire.graph.result.update
INFO 2019-02-18T10:01:56.05321Z	:: received empire.graph.result.update
INFO 2019-02-18T10:01:56.336771Z	:: received empire.graph.result.update
INFO 2019-02-18T10:01:56.686225Z	:: received empire.graph.result.update
INFO 2019-02-18T10:01:56.867126Z	:: received empire.atom.file.substitute.request
INFO empire.atom.file.substitute.request: Request {_location = GraphLocation {_filePath = "/var/folders/8v/d28f01fd1bb445_1ngwjym600000gn/T/luna4534/tutorials/TechnicalAnalysis/src/Main.luna", _breadcrumb = Breadcrumb {_items = [Definition {_nodeId = 2fa7326d-040e-47c7-b913-d5a77a36f205}]}}, _diffs = [TextDiff {_range = Just (Point {_column = 0, _row = 0},Point {_column = 0, _row = 21}), _newText = "import Dataframes.Table\n\ndef bollingerBands sum1:\n    stdDev = sum1 . eachTo \"close_std_2\" (_.at \"Close_std dev\" * 2.0)\n    bbLower = stdDev . eachTo \"BB_Lower\" (x: x.at \"Close_mean\" - x.at \"close_std_2\")\n    bbUpper = bbLower . eachTo \"BB_Upper\" (x: x.at \"Close_mean\" + x.at \"close_std_2\")\n    bbUpper\n\ndef main:\n    number1 = 20\n    data = Table . read \"./data/timeseries.txt\"\n    days1 = number1 . days\n    plot1 = data .  plot \"Date\" \"Close\" . setStyle \"-\"\n    rollingMean = rollingInterval \"Date\" days1 \"Close\" Mean\n    rollingStdDev = data . rollingInterval \"Date\" days1 \"Close\" Std\n    at = rollingStdDev . at \"Close_std dev\"\n    mergeTables = rollingMean + at\n    bollingerBandsCalc = bollingerBands mergeTables\n    fillBetweenPlot = bollingerBandsCalc . fillBetween \"Date\" \"BB_Lower\" \"BB_Upper\" . setAlpha 0.5\n    sumPlots = plot1 + fillBetweenPlot\n    None\n", _cursor = Just (Point {_column = 16, _row = 9})}]}
ERROR 2019-02-18T10:01:56.93468Z	:: error during processing request empire.atom.file.substitute.request: Breadcrumb {_items = [Definition {_nodeId = 2fa7326d-040e-47c7-b913-d5a77a36f205}]}
INFO 2019-02-18T10:01:56.936478Z	:: received empire.atom.file.substitute.update
INFO 2019-02-18T10:01:56.937049Z	:: received empire.atom.file.substitute.response

### Luna Version

Doesn't look like there's a luna-studio in the path. I'd just installed the latest 1.7 from the command line installed.

**Comment by ricardojmendez** [comment]
This error continues to pop up regardless of what I edit. I had to restart Luna.

**Comment by kustosz** [comment]
Hey @ricardojmendez, thanks for the report! Sorry for this one, it indeed is a nasty issue introduced in 1.7. I'll close this ticket now, since it's a duplicate of https://github.com/luna/luna-studio/issues/1323. The fix is already created, will get released soon. Tracked here: https://github.com/luna/luna-studio/pull/1328.

**Comment by ricardojmendez** [comment]
Closing as duplicate, will move the conversation to #1323
