### ISSUE TITLE
Install fails if MixPanel is unavailable

### ISSUE THREAD

**Issue by ricardojmendez** [luna/luna-studio#1330]
Please ensure that you are running the latest version of Luna Studio before reporting the bug! It may have been fixed since.

### General Summary

Install fails if MixPanel is unavailable.

### Steps to Reproduce

1. Block api.mixpanel.com on your firewall
2. Attempt to use the command line installed on macOS

### Expected Result

Luna is installed.

### Actual Result

Luna fails to install

MACHINENAME:Downloads ricardo$ ./luna-manager install
Please enter your email address (it is optional but will help us greatly in the early alpha stage):

```
HttpExceptionRequest Request {
host = "api.mixpanel.com"
port = 80
secure = False
requestHeaders = []
path = "/engage/"
queryString = "?data=[SOME DATA HERE]"
method = "GET"
proxy = Nothing
rawBody = False
redirectCount = 10
responseTimeout = ResponseTimeoutDefault
requestVersion = HTTP/1.1
}
(ConnectionFailure connect: does not exist (Host is down))
```

### Luna Version

1.7, command-line installer, macOS Mojave

**Comment by sylwiabr** [comment]
Issue moved to [luna/luna-manager #228](https://github.com/luna/luna-manager/issues/228) via [**ZenHub**](https://www.zenhub.com/)
