### ISSUE TITLE
Copying code from Luna Studio not possible

### ISSUE THREAD

**Issue by radeusgd** [luna/luna-studio#1370]
### General Summary
When copying a piece of code from text editor in Luna Studio, what ends up in the clipboard is the path to the currently edited file instead of the code snippet.
The result is the same when trying to paste it into other editors or Luna Studio itself, thus it's impossible to eg. duplicate a line of code.

### Steps to Reproduce
1. Create a new project.
2. Add some code.
3. Select and copy some code.
4. Try pasting it somewhere else or in a different editor.

### Expected Result
The code is pasted as-is.

### Actual Result
Path to the file that the code originated from is pasted instead.

### Luna Version
Tested on Linux at 1.8.0.36 and 1.8.0.62

**Comment by kustosz** [comment]
Unbelievably stupid typo on my part back when fixing other issues in this part of the project. Fixed on master, should be freshly baked into tomorrow's package :).
