### ISSUE TITLE
Broken package MacOS

### ISSUE THREAD

**Issue by sylwiabr** [luna/luna-studio#1385]
### General Summary

the package 1.8.0.88 is not starting on MacOS

### Expected Result

running Luna Studio
### Actual Result

Nothing happens
Actually the shortcut in `LunaStudio.app/Contents/MacOS/Luna Studio` does not work. It however works when you are running directly `LunaStudio.app/Contents/Resources/1.8.0.88/bin/main/luna-studio`

**Comment by mwu-tow** [comment]
@sylwiabr 
Works for me with path `/Applications/LunaStudio.app/Contents/MacOS/LunaStudio`. (no space between `Luna` and `Studio` — I assume it is just a typo).

What is `/Applications/LunaStudio.app/Contents/MacOS/LunaStudio` on your machine? It should be a link to `/Applications/LunaStudio.app/Contents/Resources/1.8.0.88/bin/main/luna-studio` that you said works.

How do you run both files?

Please try running both from the same command line (and the same cwd) to make sure it isn't the environment that affects behavior.

**Comment by sylwiabr** [comment]
I just double-clicking them. It is a typo. And the `/Applications/LunaStudio.app/Contents/MacOS/LunaStudio` is a link to `/Applications/LunaStudio.app/Contents/Resources/1.8.0.88/bin/main/luna-studio`

**Comment by mwu-tow** [comment]
Please try running both from the same command line (and the same cwd) to make sure it isn't the environment that affects behavior.

**Comment by mwu-tow** [comment]
Regression introduced in 1.8.0.84. Must be a side-effect of  https://github.com/luna/luna-studio/pull/1376.

**Comment by mwu-tow** [comment]
It seems that without shell `PWD` environment variable is not defined, leading to `supervisord` failing to run.
