### ISSUE TITLE
Backend does not compile anymore

### ISSUE THREAD

**Issue by mwu-tow** [luna/luna-studio#1394]
### General Summary
Backend fails to compile. The luna submodule was bumped but there are further changes necessary.

### Steps to Reproduce
Running `stack build` in `backend/` fails.

### Expected Result
The backend projects should compile.

### Actual Result

```
Error: While constructing the build plan, the following exceptions were encountered:

In the dependencies for luna-package-0.2:
    luna-path needed, but the stack configuration has no specified version (no package with that
              name found, perhaps there is a typo in a package's build-depends or an omission from
              the stack.yaml packages list?)
needed due to luna-double-representation-0.1.0.0 -> luna-package-0.2
```

etc.

**Comment by kustosz** [comment]
Just de-bump it :) From what I see it was done here https://github.com/luna/luna-studio/pull/1392 and it was done for no apparent reason (the point seems to be: bump Luna bits, which do not at all depend on the compiler changes). Proper bump will happen as part of my project manager work anyway.
