### ISSUE TITLE
Package.samples method on Windows is not resolved properly

### ISSUE THREAD

**Issue by sylwiabr** [luna/luna-studio#1398]
### Steps to Reproduce

open new project
use dataframes hint with `Table.read` method
### Expected Result

read the file from `data/samples`
### Actual Result

![image](https://user-images.githubusercontent.com/12892578/60425780-8f986c00-9bf3-11e9-9ef9-d5e732b11373.png)

### Luna Version

1.8.0.97

**Comment by mwu-tow** [comment]
Both this and #1397 are caused by Windows package containing outdated stdlib files. I will investigate.
