### ISSUE TITLE
Luna Studio startup time is super slow

### ISSUE THREAD

**Issue by wdanilo** [luna/luna-studio#250]
Recently Luna Studio startup time increased an order of magnitude in comparison to older versions. It's a little bit strange, but we need to inspect it and fix it before the final release. I've gathered few notes about this problem and I would love to ask @kustosz and @pmlodawski to really strongly investigate what is happening under the hood and preparing non-breaking (in terms of product and look & feel) solutions.

1. It seems that the slowdown COULD be (but not necessary is) connected to new plugins that are now shipped with Luna Studio. There is a list of third-party plugins we include now by default: https://github.com/luna/luna-studio-atom-config/blob/master/packages.txt . There are few new plugins made by us: "luna-dark-ui", "luna-dpi", "luna-syntax", "luna-toolbar" and two patched by us: "settings-view" and "tool-bar". All of them are available via Luna organisation github.

2. An interesting observation is that when starting new Luna Studio from terminal, we can see how backend starts and it seems that the logs from backend are printed with much bigger time offsets (which, in contrast to point 1, suggests that the problem could be connected with backend). This point, however, is not measured in aby way and could simply be not valid.

3. We can use `time cop` tool in Atom to measure how fast plugins were loaded and activated (ctrl+shift+p -> time cop). We've observed few interesting things here:
  a. The `pigments` plugin was ultra-slow on Janek's (OSX) and Sylwia's (OSX) laptops (load time > 8s), while it was loading on Kustosz's laptop (OSX) in 50ms and is loading under 100ms on all linux-based systems.
  b. If we run `time cop` on Kustosz's mac, it is clearly visible that cumulative time of all loading and startup times of the plugins is MUCH lower than the real application startup time.

In my opinion, the first step would be to investigate `time cop` results and investigate if there is ANY backend slowdown between Luna Studio 0.0.10 (the last one with proper startup time) and newest version. Next, I would disable plugin - by plugin and measure startup time (PLEASE! Be precise! measure the startup time somehow with a tool, not by feelings! Maybe a good idea would be to create a plugin, which will create a callback in atom listening for other plugins activation and will kill atom after all plugins are loaded - then you can use just normal Linux `time` command to execute the atom and wait until it gets killed). 

It is VERY important for us to understand:
1. If `time cop` results are connected to real times in any way
2. How each plugin that we ship affect the performance and what in reality causes sop big slowdown.

The best outcome from this research would be a table with 2 headers - first describing what plugins are enabled and second the REAL (not time cops) startup time. If we got it, we should discover if disabling a particular plugin would help, if the problem is connected with any our approach and if we are able to do anything with it. 

I'm strongly willing to help with this issue if we get any precise results (as described above). I would love to give support and investigate further everything, even being on vacations, so please, comment in this issue what the results are.

**Comment by piotrMocz** [comment]
The plugins were removed, the startup times are... okay-ish ;)
