### ISSUE TITLE
Unable to load atom plugins

### ISSUE THREAD

**Issue by kustosz** [luna/luna-studio#513]
Reported by a tester in a screenshot form. Will share more details as soon as I learn more.

![Screen Shot 2017-11-25 at 12.12.13.png](https://images.zenhubusercontent.com/595386f761b4ca3b0a7290e4/9750a777-f8b6-43e9-99d1-cce249242f0d)

**Comment by piotrMocz** [comment]
Closing as, it seems not to be a problem anymore.
