### ISSUE TITLE
Missed packages while building Luna Studio on Fedora 27

### ISSUE THREAD

**Issue by janklosowski** [luna/luna-studio#597]
OS: Fedora 27
Python: 2.7.14
Missed packages:
```zeromq
zeromq-devel
openssl-devel
readline-devel
zlib-devel
```

**Comment by piotrMocz** [comment]
Is there anything we can do about it? @sylwiabr @mikusp 
Does it still happen?

**Comment by sylwiabr** [comment]
I have no idea, didn't try it for a while.
