### ISSUE TITLE
The `unsaved-luna-project` default name selection is not visible when saving the project.

### ISSUE THREAD

**Issue by kustosz** [luna/luna-studio#606]
The name behaves like it is selected, it smells like it is selected, but doesn't look selected.

**Comment by pmlodawski** [comment]
It looks like Mac issue. Here is how it looks on Linux:
![image](https://user-images.githubusercontent.com/5347572/35225316-3f896e02-ff88-11e7-965d-1b086734d730.png)

**Comment by mikusp** [comment]
Duplicate of #389
