### ISSUE TITLE
Incorrect code update when connecting to arg 0 and then self of +

### ISSUE THREAD

**Issue by ljkania** [luna/luna-studio#64]
Steps to reproduce:
1. Make nodes: `node1 = +`, `node2 = 1`, `node3 = 2`
2. Connect `node2` to `Arg 0` port of `node1`
3. Connect `node3` to `Self` port of `node1`
Effect: Graph looks fine, but `node1` is now defined in code as: `node1 = nnode3de2 _ . +`

**Comment by piotrMocz** [comment]
The graph editor won't let me connect the second node to the self port (cause `node1` doesn't have one). Closing.
