### ISSUE TITLE
Luna Studio is not loading graph editor

### ISSUE THREAD

**Issue by wdanilo** [luna/luna-studio#683]
1. Open Luna Studio
2. Click Basic tutorial
3. I see blank node editor, when I click "next" on tutorial I see "please wait forever"

**Comment by wdanilo** [comment]
Guys do it still happen sometimes? @pmlodawski @mikusp ?

**Comment by kustosz** [comment]
@wdanilo you are the one reporting, so whether it still happens and how to reproduce are questions for you.

**Comment by piotrMocz** [comment]
We are not showing the Basic Tutorial anymore, so I guess this is a no-issue. Closing ;)
