### ISSUE TITLE
When trying to create a function (def) from visual editor

### ISSUE THREAD

**Issue by Severed-Infinity** [luna/luna-studio#685]
SomeParserException (Parser error: 1:1:
unexpected Token 5 0 (Var "money") :| []

CallStack (from HasCallStack):
  error, called at src/Luna/Syntax/Text/Parser/Parsing.hs:1032:19 in luna-syntax-text-parser-0.2-EhiUrnuqfI18wmiz5Qdsxa:Luna.Syntax.Text.Parser.Parsing)

while processing event

empire.graph.node.add.response

======= logs: =======

=== luna-empire-stdout---supervisor-cP3r3n.log ===
[m[95mWaiting for a message...
[m[95mMessage received
[m[92m204: 2 -> (last = 1)	:: empire.atom.file.substitute.request
[m[95[m95Wmaiting for a message...
[mSending message...
[m[95m[95mMessage sent
[mMessage received
[m[91m551: 9 -> (last = 1)	:: empire.atom.file.substitute.response
[m[91m"p\DC3\SYN\179\v\135O\226\157\142n\GS\132\203\NUL\243\SOH\149u/\145\SUB\129\233\DC3!p\128\254#\210\172\167\NUL\NUL\NUL\NUL\NUL\NUL\NULX/var/folders/y4/311dz_0d3qb7gg11_5bfb0w40000gn/T/luna/unsaved-luna-project/src/Main.luna\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\SOH\SOH\NUL\NUL\NUL\NUL\NUL\NUL\NUL\t\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\t\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\SOH\n\SOH\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\SOH\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\SOH\NUL\NUL\NUL\NUL\NUL\NUL\NUL\SOH\US,\244\142\173\218@y\131\SUB\158'\207y6\b\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\SOH\SOH\NUL\NUL\NUL\NUL\NUL\NUL\NUL\EOTtest\NUL\NUL\NUL\NUL\NUL\NUL\NUL\172def test:\n\ndef main:\n    text1 = \"Hello\"\n    list = [1, 2, 3, 4]\n    number1 = 25\n    number2 = 43.25\n    toReal1 = number1 . toReal\n    sum1 = toReal1 . + number2\n    None\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\EOTbase\ETX\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\EOTbase\ETX\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\SOH\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL"
[m[95mWaiting for a message...
[m[95mMessage received
[m[92m205: 2 -> (last = 1)	:: empire.atom.file.substitute.request
[m[9[59m5mWaiting for a message...
[mSending message...
[m[95mMessage sent
[9[5mmMessage received
[m[91m552: 9 -> (last = 1)	:: empire.atom.file.substitute.response
[m[91m" \154J\255\158FG\150\131\221\SUB\DC3\SO5\SO\227\SOH\149u/\145\SUB\129\233\DC3!p\128\254#\210\172\167\NUL\NUL\NUL\NUL\NUL\NUL\NULX/var/folders/y4/311dz_0d3qb7gg11_5bfb0w40000gn/T/luna/unsaved-luna-project/src/Main.luna\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\SOH\SOH\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\SOH\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\SOH\NUL\NUL\NUL\NUL\NUL\NUL\NUL\EOT    \SOH\NUL\NUL\NUL\NUL\NUL\NUL\NUL\EOT\NUL\NUL\NUL\NUL\NUL\NUL\NUL\SOH\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\SOH\NUL\NUL\NUL\NUL\NUL\NUL\NUL\SOH\US,\244\142\173\218@y\131\SUB\158'\207y6\b\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\SOH\SOH\NUL\NUL\NUL\NUL\NUL\NUL\NUL\EOTtest\NUL\NUL\NUL\NUL\NUL\NUL\NUL\176def test:\n    \ndef main:\n    text1 = \"Hello\"\n    list = [1, 2, 3, 4]\n    number1 = 25\n    number2 = 43.25\n    toReal1 = number1 . toReal\n    sum1 = toReal1 . + number2\n    None\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\EOTbase\ETX\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\EOTbase\ETX\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\SOH\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL"
[m[95mWaiting for a message...
[m[95mMessage received
[m[92m206: 2 -> (last = 1)	:: empire.atom.file.substitute.request
[m[9[59m5mWaiting for a message...
[mSending message...
[m[95mMessage sen[t9
5mM[emssage received
[m[91m553: 9 -> (last = 1)	:: empire.atom.file.substitute.response
[m[91m"\201\ETB\139Lf\179A\NUL\167\130gW\DC4\175t\198\SOH\149u/\145\SUB\129\233\DC3!p\128\254#\210\172\167\NUL\NUL\NUL\NUL\NUL\NUL\NULX/var/folders/y4/311dz_0d3qb7gg11_5bfb0w40000gn/T/luna/unsaved-luna-project/src/Main.luna\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\SOH\SOH\NUL\NUL\NUL\NUL\NUL\NUL\NUL\EOT\NUL\NUL\NUL\NUL\NUL\NUL\NUL\SOH\NUL\NUL\NUL\NUL\NUL\NUL\NUL\EOT\NUL\NUL\NUL\NUL\NUL\NUL\NUL\SOH\NUL\NUL\NUL\NUL\NUL\NUL\NUL\EOTsome\SOH\NUL\NUL\NUL\NUL\NUL\NUL\NUL\b\NUL\NUL\NUL\NUL\NUL\NUL\NUL\SOH\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\SOH\NUL\NUL\NUL\NUL\NUL\NUL\NUL\STX\US,\244\142\173\218@y\131\SUB\158'\207y6\b\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\SOH\SOH\NUL\NUL\NUL\NUL\NUL\NUL\NUL\EOTtest\NUL\NUL\NUL\NUL\NUL\NUL\NUL\DC2def test:\n    some\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\EOTbase\ETX\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\EOTbase\ETX\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\SOH\247f\220\152\STX/FA\157\DC4\RS6\225\187N\ESC\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\SOH\SOH\NUL\NUL\NUL\NUL\NUL\NUL\NUL\EOTmain\NUL\NUL\NUL\NUL\NUL\NUL\NUL\161def main:\n    text1 = \"Hello\"\n    list = [1, 2, 3, 4]\n    number1 = 25\n    number2 = 43.25\n    toReal1 = number1 . toReal\n    sum1 = toReal1 . + number2\n    None\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\EOTbase\ETX\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\EOTbase\ETX\NUL\SOH\SOH\NUL\NUL\NUL\NUL\NUL\NUL\NUL\a\NUL\NUL\NUL\NUL\NUL\NUL\SYN\255\255\255\255\255\255\255\211\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\SOH\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL"
[m[95mWaiting for a message...
[m[95mMessage received
[m[92m207: 2 -> (last = 1)	:: empire.atom.file.substitute.request
[m[9[59m5Wmaiting for a message...
[Smending message...
[m[95mMessage sent
[m[95mMessage received
[m[91m554: 9 -> (last = 1)	:: empire.atom.file.substitute.response
[m[91m"\ACK\150\131\&5cW@p\149\174\SYN!\151\248v?\SOH\149u/\145\SUB\129\233\DC3!p\128\254#\210\172\167\NUL\NUL\NUL\NUL\NUL\NUL\NULX/var/folders/y4/311dz_0d3qb7gg11_5bfb0w40000gn/T/luna/unsaved-luna-project/src/Main.luna\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\SOH\SOH\NUL\NUL\NUL\NUL\NUL\NUL\NUL\b\NUL\NUL\NUL\NUL\NUL\NUL\NUL\SOH\NUL\NUL\NUL\NUL\NUL\NUL\NUL\b\NUL\NUL\NUL\NUL\NUL\NUL\NUL\SOH\NUL\NUL\NUL\NUL\NUL\NUL\NUL\STX =\SOH\NUL\NUL\NUL\NUL\NUL\NUL\NUL\n\NUL\NUL\NUL\NUL\NUL\NUL\NUL\SOH\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\STX\US,\244\142\173\218@y\131\SUB\158'\207y6\b\247f\220\152\STX/FA\157\DC4\RS6\225\187N\ESC\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\STX\NUL\NUL\NUL\NUL\NUL\NUL\SOH\tSomeParserException (Parser error: 5:15:\nunexpected Token 4 1 (Var \"some\") :| []\n\nCallStack (from HasCallStack):\n  error, called at src/Luna/Syntax/Text/Parser/Parsing.hs:1032:19 in luna-syntax-text-parser-0.2-EhiUrnuqfI18wmiz5Qdsxa:Luna.Syntax.Text.Parser.Parsing)\NUL"
[m[95mWaiting for a message...
[m[95mMessage received
[m[92m208: 2 -> (last = 1)	:: empire.atom.file.substitute.request
[m[95m[W9a5imting for a message...
[mSending message...
[m[95mMessage sent
[m[95mMessage received
[m[91m555: 9 -> (last = 1)	:: empire.atom.file.substitute.response
[m[91m"\213lQ\216\243\138J_\134\144\225\&8\158\208\212\211\SOH\149u/\145\SUB\129\233\DC3!p\128\254#\210\172\167\NUL\NUL\NUL\NUL\NUL\NUL\NULX/var/folders/y4/311dz_0d3qb7gg11_5bfb0w40000gn/T/luna/unsaved-luna-project/src/Main.luna\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\SOH\SOH\NUL\NUL\NUL\NUL\NUL\NUL\NUL\n\NUL\NUL\NUL\NUL\NUL\NUL\NUL\SOH\NUL\NUL\NUL\NUL\NUL\NUL\NUL\n\NUL\NUL\NUL\NUL\NUL\NUL\NUL\SOH\NUL\NUL\NUL\NUL\NUL\NUL\NUL\SOH \SOH\NUL\NUL\NUL\NUL\NUL\NUL\NUL\v\NUL\NUL\NUL\NUL\NUL\NUL\NUL\SOH\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\STX\NUL\NUL\NUL\NUL\NUL\NUL\SOH\tSomeParserException (Parser error: 5:15:\nunexpected Token 4 1 (Var \"some\") :| []\n\nCallStack (from HasCallStack):\n  error, called at src/Luna/Syntax/Text/Parser/Parsing.hs:1032:19 in luna-syntax-text-parser-0.2-EhiUrnuqfI18wmiz5Qdsxa:Luna.Syntax.Text.Parser.Parsing)\NUL"
[m[95mWaiting for a message...
[m[95mMessage received
[m[92m209: 2 -> (last = 1)	:: empire.atom.file.substitute.request
[m[9[59m5mWaiting for a message...
[Smending message...
[m[95mMessage sent
[m[95mMessage received
[m[91m556: 9 -> (last = 1)	:: empire.atom.file.substitute.response
[m[91m"\SYN\180L#\183\146D\194\180\158x\171\251\140f2\SOH\149u/\145\SUB\129\233\DC3!p\128\254#\210\172\167\NUL\NUL\NUL\NUL\NUL\NUL\NULX/var/folders/y4/311dz_0d3qb7gg11_5bfb0w40000gn/T/luna/unsaved-luna-project/src/Main.luna\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\SOH\SOH\NUL\NUL\NUL\NUL\NUL\NUL\NUL\v\NUL\NUL\NUL\NUL\NUL\NUL\NUL\SOH\NUL\NUL\NUL\NUL\NUL\NUL\NUL\v\NUL\NUL\NUL\NUL\NUL\NUL\NUL\SOH\NUL\NUL\NUL\NUL\NUL\NUL\NUL\STX\"\"\SOH\NUL\NUL\NUL\NUL\NUL\NUL\NUL\f\NUL\NUL\NUL\NUL\NUL\NUL\NUL\SOH\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\SOH\NUL\NUL\NUL\NUL\NUL\NUL\NUL\STX\US,\244\142\173\218@y\131\SUB\158'\207y6\b\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\SOH\SOH\NUL\NUL\NUL\NUL\NUL\NUL\NUL\EOTtest\NUL\NUL\NUL\NUL\NUL\NUL\NUL\ETBdef test:\n    some = \"\"\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\EOTbase\ETX\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\EOTbase\ETX\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\SOH\247f\220\152\STX/FA\157\DC4\RS6\225\187N\ESC\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\SOH\SOH\NUL\NUL\NUL\NUL\NUL\NUL\NUL\EOTmain\NUL\NUL\NUL\NUL\NUL\NUL\NUL\161def main:\n    text1 = \"Hello\"\n    list = [1, 2, 3, 4]\n    number1 = 25\n    number2 = 43.25\n    toReal1 = number1 . toReal\n    sum1 = toReal1 . + number2\n    None\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\EOTbase\ETX\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\EOTbase\ETX\NUL\SOH\SOH\NUL\NUL\NUL\NUL\NUL\NUL\NUL\a\NUL\NUL\NUL\NUL\NUL\NUL\SYN\255\255\255\255\255\255\255\211\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\SOH\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL"
[m[95mWaiting for a message...
[m[95mMessage received
[m[92m210: 2 -> (last = 1)	:: empire.atom.file.substitute.request
[m[9[59m5mWaiting for a message...
[Smend[i9n5gm message...
[Mmessage received
[m[92m211: 2 -> (last = 1)	:: empire.atom.file.substitute.request
[95[mmMessage sent
[m[9[59m5mWaiting for a message...
[m[95mSending message...
[Mmessage received
[m[91m557: 9 -> (last = 1)	:: empire.atom.file.substitute.response
[m[95mMessage sent
[m[91m"O%\246\204|\241B\227\170^\249m\245\226\181\195\SOH\149u/\145\SUB\129\233\DC3!p\128\254#\210\172\167\NUL\NUL\NUL\NUL\NUL\NUL\NULX/var/folders/y4/311dz_0d3qb7gg11_5bfb0w40000gn/T/luna/unsaved-luna-project/src/Main.luna\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\SOH\SOH\NUL\NUL\NUL\NUL\NUL\NUL\NUL\f\NUL\NUL\NUL\NUL\NUL\NUL\NUL\SOH\NUL\NUL\NUL\NUL\NUL\NUL\NUL\f\NUL\NUL\NUL\NUL\NUL\NUL\NUL\SOH\NUL\NUL\NUL\NUL\NUL\NUL\NUL\ETXsom\SOH\NUL\NUL\NUL\NUL\NUL\NUL\NUL\SI\NUL\NUL\NUL\NUL\NUL\NUL\NUL\SOH\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\SOH\NUL\NUL\NUL\NUL\NUL\NUL\NUL\SOH\US,\244\142\173\218@y\131\SUB\158'\207y6\b\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\SOH\SOH\NUL\NUL\NUL\NUL\NUL\NUL\NUL\EOTtest\NUL\NUL\NUL\NUL\NUL\NUL\NUL\SUBdef test:\n    some = \"som\"\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\EOTbase\ETX\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\EOTbase\ETX\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\SOH\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL"
[m[95mWaiting for a message...
[m[95mMessage received
[m[91m558: 9 -> (last = 1)	:: empire.atom.file.substitute.response
[m[91m"\156\149\CAN`\162rF\188\164\158\226oMWA%\SOH\149u/\145\SUB\129\233\DC3!p\128\254#\210\172\167\NUL\NUL\NUL\NUL\NUL\NUL\NULX/var/folders/y4/311dz_0d3qb7gg11_5bfb0w40000gn/T/luna/unsaved-luna-project/src/Main.luna\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\SOH\SOH\NUL\NUL\NUL\NUL\NUL\NUL\NUL\SI\NUL\NUL\NUL\NUL\NUL\NUL\NUL\SOH\NUL\NUL\NUL\NUL\NUL\NUL\NUL\SI\NUL\NUL\NUL\NUL\NUL\NUL\NUL\SOH\NUL\NUL\NUL\NUL\NUL\NUL\NUL\SOHe\SOH\NUL\NUL\NUL\NUL\NUL\NUL\NUL\DLE\NUL\NUL\NUL\NUL\NUL\NUL\NUL\SOH\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\SOH\NUL\NUL\NUL\NUL\NUL\NUL\NUL\SOH\US,\244\142\173\218@y\131\SUB\158'\207y6\b\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\SOH\SOH\NUL\NUL\NUL\NUL\NUL\NUL\NUL\EOTtest\NUL\NUL\NUL\NUL\NUL\NUL\NUL\ESCdef test:\n    some = \"some\"\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\EOTbase\ETX\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\EOTbase\ETX\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\SOH\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL"
[m[95mWaiting for a message...
[m[95mMessage received
[m[92m212: 2 -> (last = 1)	:: empire.atom.file.substitute.request
[m[[9955mmWaiting for a message...
[Smending message...
[m[95mMessage sent
[m[95mMessage received
[m[91m559: 9 -> (last = 1)	:: empire.atom.file.substitute.response
[m[91m"f\171\162s\216)@\202\161\&1S\179!\233\v\SUB\SOH\149u/\145\SUB\129\233\DC3!p\128\254#\210\172\167\NUL\NUL\NUL\NUL\NUL\NUL\NULX/var/folders/y4/311dz_0d3qb7gg11_5bfb0w40000gn/T/luna/unsaved-luna-project/src/Main.luna\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\SOH\SOH\NUL\NUL\NUL\NUL\NUL\NUL\NUL\DC1\NUL\NUL\NUL\NUL\NUL\NUL\NUL\SOH\NUL\NUL\NUL\NUL\NUL\NUL\NUL\DC1\NUL\NUL\NUL\NUL\NUL\NUL\NUL\SOH\NUL\NUL\NUL\NUL\NUL\NUL\NUL\ENQ\n    \SOH\NUL\NUL\NUL\NUL\NUL\NUL\NUL\EOT\NUL\NUL\NUL\NUL\NUL\NUL\NUL\STX\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\SOH\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL"
[m[95mWaiting for a message...
[m[95mMessage received
[m[92m213: 2 -> (last = 1)	:: empire.graph.collaboration.update
[m[95mWaiting for a message...
[m[95mMessage received
[m[92m214: 2 -> (last = 1)	:: empire.graph.node.add.request
[m[91mError processing request: empire.graph.node.add.request: SomeParserException (Parser error: 1:1:
unexpected Token 5 0 (Var "money") :| []

CallStack (from HasCallStack):
  error, called at src/Luna/Syntax/Text/Parser/Parsing.hs:1032:19 in luna-syntax-text-parser-0.2-EhiUrnuqfI18wmiz5Qdsxa:Luna.Syntax.Text.Parser.Parsing)
[m[9[59m5mWaiting for a message...
[Smending message...
[m[95mMessage sent
[m[95mMessage received
[m[91m560: 9 -> (last = 1)	:: empire.graph.node.add.response
[m[91m"I\GSE\194\159\166HM\130~i\217\DC3\225\131\SOH\SOH\246\199j\134yC\240*\146j\166\228_\254\223\186\NUL\NUL\NUL\NUL\NUL\NUL\NULX/var/folders/y4/311dz_0d3qb7gg11_5bfb0w40000gn/T/luna/unsaved-luna-project/src/Main.luna\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NULh\SI\205\SYNj\153A\STX\151\177\167=\GS\168\v\143\NUL\NUL\NUL\NUL\NUL\NUL\NUL\ACKmoney:\SOH\SOH\NUL\NUL\NUL\NUL\NUL\NUL\NUL\a\NUL\NUL\NUL\NUL\NUL\NUL\DC4\255\255\255\255\255\255\255\212\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\SOH\SOH\NUL\NUL\NUL\NUL\NUL\NUL\SOH\tSomeParserException (Parser error: 1:1:\nunexpected Token 5 0 (Var \"money\") :| []\n\nCallStack (from HasCallStack):\n  error, called at src/Luna/Syntax/Text/Parser/Parsing.hs:1032:19 in luna-syntax-text-parser-0.2-EhiUrnuqfI18wmiz5Qdsxa:Luna.Syntax.Text.Parser.Parsing)"
[m[95mWaiting for a message...
[m

**Comment by wdanilo** [comment]
It seems like youve got a simple syntax error in your code, would you mind share the code with me here? 
By the way, the parser error messages should be nicer, we will work on it soon.

**Comment by ricardopieper** [comment]
Seems related to https://github.com/luna/luna-studio/issues/700

**Comment by wdanilo** [comment]
@Severed-Infinity I strongly believe @ricardopieper is right. in #700 I've described that this is not a bug and why it happens. However we will need to fix the error message to make it more clear. Please refer to that issue and if it does not solve yours, reopen.
