### ISSUE TITLE
When opening Luna Studio, 'Fetching tutorials list...' stays empty

### ISSUE THREAD

**Issue by flacle** [luna/luna-studio#692]
This is on OSX High Sierra, any guidance as to how I can start to debug this issue is appreciated, conversely let me know what additional information from my system configuration is missing.

**Comment by kustosz** [comment]
This one is kind of embarassing. GitHub preemptively locked our API keys, assuming it's a security risk (while the scope of the key is exactly what we've intended). This is a duplicate of #684, so I'm closing it for now.
For now you can clone the tutorials from https://github.com/luna-packages and `Cmd/Ctrl-O` open these projects from Luna Studio. Not that handy, but you can get all the content.

**Comment by flacle** [comment]
@kustosz great there is a workaround 👍 . No worries, I don't think it is embarrassing, Meltdown and Spectre on the other hand...

**Comment by wdanilo** [comment]
@flacle if you compare this issue to meltdown and spectre I'm starting to worry about what Luna does to your PC :D
