### ISSUE TITLE
installing failed

### ISSUE THREAD

**Issue by RainVector** [luna/luna-studio#697]
When I install luna-studio 1.0 beta. it produce an erro: Prelude.head: empty list
![wechat image_20180117150458](https://user-images.githubusercontent.com/6712304/35029904-ff60161c-fb97-11e7-9259-87b242d0e3df.png)

**Comment by gobse** [comment]
Same here.

Windows 10

In normal and admin mode

**Comment by alexbiehl** [comment]
Same here on Windows 10.

**Comment by aolko** [comment]
same here, win10x64

**Comment by wdanilo** [comment]
We're working on it guys!

**Comment by kustosz** [comment]
Hey! The issue should be fixed now, please try redownloading the installer from http://packages.luna-lang.org/windows/lunaInstaller.zip
