### ISSUE TITLE
Error: Another program is already listening on a port that one of our HTTP servers is configured to use

### ISSUE THREAD

**Issue by d4nyll** [luna/luna-studio#701]
After running the `lunainstaller` binary, I tried to run the `luna-studio` binary inside my home directory, but it is throwing an error saying `Another program is already listening on a port that one of our HTTP servers is configured to use`

```
$ ~/.luna/bin/luna-studio/1.0/luna-studio 
unix:///tmp/supervisor.sock no such file
Error: Another program is already listening on a port that one of our HTTP servers is configured to use.  Shut this program down first before starting supervisord.
For help, use /tmp/.mount_luna-swK56od/usr/third-party/supervisord/supervisord -h
luna-studio: Received ExitFailure 2 when running
Shell command: /tmp/.mount_luna-swK56od/usr/third-party/supervisord/supervisord -n -c supervisord-package.conf
Run from: /tmp/.mount_luna-swK56od/usr/config/supervisor
```

I have checked my bound ports but none of them are listening to common ports like `3000` or `8000` or `8080` etc, nor any of the ports I've found specified in this repo - `8088`, `30530`, `30531`, `30532`.

I have checked that `supervisor` service is running:

```
$ pgrep -fl supervisor
27312 supervisord
```

There are no errors in `/var/log/supervisor/supervisord.log`

So which port should I clear up? And would it be possible to provide a more informative error message telling the end user exactly the port in question.

---

My system info:

```
$ uname -a
Linux 4.13.0-25-generic #29-Ubuntu SMP Mon Jan 8 21:14:41 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by wdanilo** [comment]
Thanks for reporting it! By the way, we should not use the port `8080`, if we use it, it is another fix to do while fixing this issue. Moreover, we should provide configuration which ports LunaStudio uses, so if we try to use ports already in use by some end-user applications, he should be able to re-configure Luna Studio easily.
