### ISSUE TITLE
Connection closed.

### ISSUE THREAD

**Issue by o1lo01ol1o** [luna/luna-studio#706]
Connection closed.

======= logs: =======

=== luna-empire-stdout---supervisor-EbDyhU.log ===
[m5: 7 -> (last = 1)	:: empire.graph.node.ty[p9e5cmheck
[mMessage sent
[m[95m[91m"\NUL\NUL\NUL\NUL\NUL\NUL\NULX/var/folders/tm/xscpb5sx7_z8mq20wlq12bpc0000gn/T/luna/unsaved-luna-project/src/Main.luna\NUL\NUL\NUL\NUL\NUL\NUL\NUL\SOH\NULqD\155\162h\229B\166\153\163u\231+\144\SUBR\STX\198\180\251\222~\236A\ETB\182f\214\164\217D\133\236\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL"
[m[95mSending message...
[mWaiting for a message...
[m[95mMessage received
[95m[mMes[s9a1gme sent
[m6: 7 -> (last = 1)	:: empire.graph.node.typecheck
[m[91m"\NUL\NUL\NUL\NUL\NUL\NUL\NULX/var/folders/tm/xscpb5sx7_z8mq20wlq12bpc0000gn/T/luna/unsaved-luna-project/src/Main.luna\NUL\NUL\NUL\NUL\NUL\NUL\NUL\SOH\NULqD\155\162h\229B\166\153\163u\231+\144\SUBR\SOHW\219\STX\149\228<K\ETB\164\194\188o7\217\195\RS\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\ACKoutput\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\EOTNone\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\STX\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\EOTNone"
[m[95mWaiting for a message...
[m[95mMessage received
[m[91m7: 7 -> (last = 1)	:: empire.graph.node.typecheck
[m[91m"\NUL\NUL\NUL\NUL\NUL\NUL\NULX/var/folders/tm/xscpb5sx7_z8mq20wlq12bpc0000gn/T/luna/unsaved-luna-project/src/Main.luna\NUL\NUL\NUL\NUL\NUL\NUL\NUL\SOH\NULqD\155\162h\229B\166\153\163u\231+\144\SUBR\NUL\208\NAK\218x-\145M\205\128\228/\EM\153%e\NAK\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\ENQalias\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\EOTText\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\STX\SOH\ETX\NUL\NUL\NUL\NUL\NUL\NUL\NUL\rHello, World!\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\ENQhello\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\EOTText\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL"
[m[95mWaiting for a message...
[m[95mMessage received
[m[92m5: 3 -> (last = 1)	:: empire.graph.nodesearch.request
[m[95mWaiting for a message...
[m[95mMessage received
[m[92m6: 3 -> (last = 1)	:: empire.graph.node.updateMeta.update
[m[95mWaiting for a message...
[m[95mMessage received
[m[92m7: 3 -> (last = 1)	:: empire.graph.program.request
[m[95m[95Wmaiting for a message...
[mSending message...
[m[95mMessage sent
[m[95mMessage received
[m[91m8: 7 -> (last = 1)	:: empire.graph.program.response
[m[91m"\186I\205\142[\130B\206\136\244\206\237g\221\EM\255\SOH\214\136@\216\f\207\151\158>I\150\236G.\201\184\NUL\NUL\NUL\NUL\NUL\NUL\NULX/var/folders/tm/xscpb5sx7_z8mq20wlq12bpc0000gn/T/luna/unsaved-luna-project/src/Main.luna\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\SOH\NUL\NUL\NUL\NUL\NUL\NUL\NULX/var/folders/tm/xscpb5sx7_z8mq20wlq12bpc0000gn/T/luna/unsaved-luna-project/src/Main.luna\NUL\NUL\NUL\NUL\NUL\NUL\NUL\SOH\NULqD\155\162h\229B\166\153\163u\231+\144\SUBR\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\EOT\NUL\NUL\NUL\NUL\NUL\NUL\NUL\EOT\SOH\SOH\NUL\NUL\NUL\NUL\NUL\NUL\NUL\a\NUL\NUL\NUL\NUL\NUL\NUL\DLE\255\255\255\255\255\255\255\204\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\EOT\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\SOH\SOH\NUL\NUL\NUL\NUL\NUL\NUL\NUL\a\NUL\NUL\NUL\NUL\NUL\NUL\DLE\255\255\255\255\255\255\255\204\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\EOT\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\SOH\SOH\NUL\NUL\NUL\NUL\NUL\NUL\NUL\a\NUL\NUL\NUL\NUL\NUL\NUL\DLE\255\255\255\255\255\255\255\204\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\EOT\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\SOH\SOH\NUL\NUL\NUL\NUL\NUL\NUL\NUL\a\NUL\NUL\NUL\NUL\NUL\NUL\DLE\255\255\255\255\255\255\255\204\NUL\NUL\NUL\NUL\NUL\NUL\NUL\EOT\NUL\NUL\NUL\NUL\NUL\NUL\NUL\EOT\SOH\SOH\NUL\NUL\NUL\NUL\NUL\NUL\NUL\a\NUL\NUL\NUL\NUL\NUL\NUL\DLE\255\255\255\255\255\255\255\204\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\EOT\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\SOH\SOH\NUL\NUL\NUL\NUL\NUL\NUL\NUL\a\NUL\NUL\NUL\NUL\NUL\NUL\DLE\255\255\255\255\255\255\255\204\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\EOT\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\SOH\SOH\NUL\NUL\NUL\NUL\NUL\NUL\NUL\a\NUL\NUL\NUL\NUL\NUL\NUL\DLE\255\255\255\255\255\255\255\204\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\EOT\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\SOH\SOH\NUL\NUL\NUL\NUL\NUL\NUL\NUL\a\NUL\NUL\NUL\NUL\NUL\NUL\DLE\255\255\255\255\255\255\255\204\NUL\NUL\NUL\NUL\NUL\NUL\NUL\STX\NUL\NUL\NUL\SOH\NUL\NUL\NUL\NUL\NUL\NUL\NUL\SOHqD\155\162h\229B\166\153\163u\231+\144\SUBR\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\SOH\SOH\NUL\NUL\NUL\NUL\NUL\NUL\NUL\EOTmain\NUL\NUL\NUL\NUL\NUL\NUL\NUL.def main:\n    hello = \"Hello, World!\"\n    None\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\EOTbase\ETX\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\EOTbase\ETX\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\SOH\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL.def main:\n    hello = \"Hello, World!\"\n    None\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\STX\NUL\NUL\NUL\NUL\NUL\NUL\NUL\ACKNative\NUL\NUL\NUL\NUL\NUL\NUL\NUL\bStd.Base\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\EOT\NUL\NUL\NUL\NUL\NUL\NUL\NUL\EOT\SOH\SOH\NUL\NUL\NUL\NUL\NUL\NUL\NUL\a\NUL\NUL\NUL\NUL\NUL\NUL\DLE\255\255\255\255\255\255\255\204\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\EOT\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\SOH\SOH\NUL\NUL\NUL\NUL\NUL\NUL\NUL\a\NUL\NUL\NUL\NUL\NUL\NUL\DLE\255\255\255\255\255\255\255\204\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\EOT\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\SOH\SOH\NUL\NUL\NUL\NUL\NUL\NUL\NUL\a\NUL\NUL\NUL\NUL\NUL\NUL\DLE\255\255\255\255\255\255\255\204\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\EOT\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\SOH\SOH\NUL\NUL\NUL\NUL\NUL\NUL\NUL\a\NUL\NUL\NUL\NUL\NUL\NUL\DLE\255\255\255\255\255\255\255\204\NUL\NUL\NUL\NUL\NUL\NUL\NUL\EOT\NUL\NUL\NUL\NUL\NUL\NUL\NUL\EOT\SOH\SOH\NUL\NUL\NUL\NUL\NUL\NUL\NUL\a\NUL\NUL\NUL\NUL\NUL\NUL\DLE\255\255\255\255\255\255\255\204\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\EOT\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\SOH\SOH\NUL\NUL\NUL\NUL\NUL\NUL\NUL\a\NUL\NUL\NUL\NUL\NUL\NUL\DLE\255\255\255\255\255\255\255\204\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\EOT\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\SOH\SOH\NUL\NUL\NUL\NUL\NUL\NUL\NUL\a\NUL\NUL\NUL\NUL\NUL\NUL\DLE\255\255\255\255\255\255\255\204\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\EOT\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\SOH\SOH\NUL\NUL\NUL\NUL\NUL\NUL\NUL\a\NUL\NUL\NUL\NUL\NUL\NUL\DLE\255\255\255\255\255\255\255\204\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NULX/var/folders/tm/xscpb5sx7_z8mq20wlq12bpc0000gn/T/luna/unsaved-luna-project/src/Main.luna\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL"
[m[95mWaiting for a message...
[m[95mMessage received
[m[92m8: 3 -> (last = 1)	:: empire.graph.nodesearch.request
[m[95mWaiting for a message...
[m[95mMessage received
[m[92m9: 3 -> (last = 1)	:: empire.graph.collaboration.update
[m[95mWaiting for a message...
[m[95mMessage received
[m[92m10: 3 -> (last = 1)	:: empire.graph.program.request
[m[95m[95mWaiting for a message...
[mSending message...
[m[95mMessage sent
[m[95mMessage received
[m[91m9: 7 -> (last = 1)	:: empire.graph.program.response
[m[91m"\214q!\131\173\185G\129\141M\176\164\245\160\175\212\SOH\214\136@\216\f\207\151\158>I\150\236G.\201\184\NUL\NUL\NUL\NUL\NUL\NUL\NULX/var/folders/tm/xscpb5sx7_z8mq20wlq12bpc0000gn/T/luna/unsaved-luna-project/src/Main.luna\NUL\NUL\NUL\NUL\NUL\NUL\NUL\SOH\NULqD\155\162h\229B\166\153\163u\231+\144\SUBR\SOH\NUL\NUL\NUL\NUL\NUL\NUL\NULX/var/folders/tm/xscpb5sx7_z8mq20wlq12bpc0000gn/T/luna/unsaved-luna-project/src/Main.luna\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NU...

**Comment by wdanilo** [comment]
Could you please describe exact steps you've taken to get this error please?

**Comment by o1lo01ol1o** [comment]
I can't reproduce.   I suspect there was a zombie Atom process somewhere.  Will open if it occurs again.
