### ISSUE TITLE
Install issues on MacOS (10.12.6) from a non admin user

### ISSUE THREAD

**Issue by gcsolaroli** [luna/luna-studio#713]
I have tried to install Luna-Lang on my Mac (Version 10.12.6 - 16G1114) from with my account, but I got this error:

mv: rename /var/folders/lm/5mrv189135d24wrvjv1dpcp40000gp/T/luna/luna-studio to /Applications/LunaStudio.app/Contents/Resources/1.0.1: Permission denied
error running: mv /var/folders/lm/5mrv189135d24wrvjv1dpcp40000gp/T/luna/luna-studio /Applications/LunaStudio.app/Contents/Resources/1.0.1
exit status: 1
stderr: mv: rename /var/folders/lm/5mrv189135d24wrvjv1dpcp40000gp/T/luna/luna-studio to /Applications/LunaStudio.app/Contents/Resources/1.0.1: Permission denied

<img width="402" alt="Installation error" src="https://user-images.githubusercontent.com/95118/35085887-cc9eb380-fc2a-11e7-99e6-a98204b32889.png">

<img width="457" alt="account details" src="https://user-images.githubusercontent.com/95118/35085886-cc83fe78-fc2a-11e7-81f2-ae2101f0989f.png">

Yesterday I run the installer using the administrator account, but when I try to run the application from my regular account I get this other error:
Uncaught TypeError: parsed.forEach is not a function
/Users/giulio.cesare/.luna/config/luna-studio/1.0/atom/packages/luna-studio/lib/projects.coffee:160

<img width="688" alt="error running luna-studio from the non-admin user" src="https://user-images.githubusercontent.com/95118/35085981-2c3688c2-fc2b-11e7-8bd8-984fb77e7c00.png">

**Comment by mikusp** [comment]
Thank you for your bug report.

Your second issue is resolved in a package version 1.0.1 that you should be able to install. You need to run installer once again, choose 1.0.1 and install.

As for the first error, I will assign this issue to our Mac specialists. You should hear from them shortly.

**Comment by gcsolaroli** [comment]
I confirm that the second issues has been solved installing version 1.0.1-nightly.
Thanks
