### ISSUE TITLE
My experience with the luna editor

### ISSUE THREAD

**Issue by timthelion** [luna/luna-studio#716]
Hello,

I've just tried out the luna editor and made a little screen cast showing my struggles to use it http://ipfs.hobbs.cz/ipfs/QmfTgBQj52n7m5qx6GhGVwfchNzQUXuJraMGdT9haDWQsf

I found the download process to be somewhat confusing. First I looked through the menu [here](http://www.luna-lang.org/), and didn't see any install link. When I opened up the docs, however, I was greeted with a big orange "Install" button, on the installation page https://luna-lang.gitbooks.io/docs/content/installation.html . I tried clicking that button, but it didn't seem to work ;). Then I realized that it was a screen shot.

After upping my reading comprehension skills, I tried clicking on the "website" link, which brought me back where I had started. After trying the browse sources link, I finally managed to download and run luna-manager for linux. Here is the output of ./luna-manager info

````
$ ./luna-manager info
src/Luna/Manager/Command.hs:(26,5)-(30,133): Non-exhaustive patterns in case
````
Here is the textual output of runing the luna-studio command.

````
./bin/luna-studio/1.0/luna-studio 
unix:///tmp/supervisor.sock no such file
2018-01-18 14:41:24,654 INFO RPC interface 'supervisor' initialized
2018-01-18 14:41:24,654 CRIT Server 'inet_http_server' running without any HTTP authentication checking
2018-01-18 14:41:24,654 INFO RPC interface 'supervisor' initialized
2018-01-18 14:41:24,654 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2018-01-18 14:41:24,654 INFO supervisord started with pid 2458
2018-01-18 14:41:25,657 INFO spawned: 'luna-atom-kill' with pid 2462
2018-01-18 14:41:25,658 INFO spawned: 'luna-atom' with pid 2463
2018-01-18 14:41:25,660 INFO spawned: 'ws-connector' with pid 2464
2018-01-18 14:41:25,662 INFO spawned: 'broker' with pid 2465
2018-01-18 14:41:25,664 INFO spawned: 'luna-empire' with pid 2466
2018-01-18 14:41:25,666 INFO spawned: 'logger' with pid 2467
2018-01-18 14:41:25,668 INFO spawned: 'undo-redo' with pid 2468
2018-01-18 14:41:25,793 INFO success: luna-atom entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2018-01-18 14:41:26,733 INFO success: luna-atom-kill entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2018-01-18 14:41:26,733 INFO success: ws-connector entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2018-01-18 14:41:26,733 INFO success: broker entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2018-01-18 14:41:26,733 INFO success: luna-empire entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2018-01-18 14:41:26,734 INFO success: logger entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2018-01-18 14:41:26,734 INFO success: undo-redo entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2018-01-18 14:41:48,139 INFO exited: luna-atom (exit status 0; expected)
2018-01-18 14:41:49,141 WARN luna-atom-kill: bad result line: u'This line kills supervisor: ver:3.0 server:supervisor serial:0 pool:luna-atom_exit poolserial:0 eventname:PROCESS_STATE_EXITED len:80'
2018-01-18 14:41:49,141 WARN luna-atom-kill: has entered the UNKNOWN state and will no longer receive events, this usually indicates the process violated the eventlistener protocol
2018-01-18 14:41:49,141 WARN received SIGQUIT indicating exit request
2018-01-18 14:41:49,141 INFO waiting for luna-atom-kill, ws-connector, broker, luna-empire, logger, undo-redo to die
2018-01-18 14:41:49,142 INFO stopped: undo-redo (terminated by SIGTERM)
2018-01-18 14:41:49,143 INFO stopped: logger (terminated by SIGTERM)
2018-01-18 14:41:49,150 INFO stopped: luna-empire (terminated by SIGTERM)
2018-01-18 14:41:49,151 INFO stopped: broker (terminated by SIGTERM)
2018-01-18 14:41:49,152 INFO stopped: ws-connector (terminated by SIGTERM)
2018-01-18 14:41:50,154 INFO stopped: luna-atom-kill (terminated by SIGTERM)
````

For context, here is uname -a

````
$ uname -a
Linux yoga 4.9.0-0.bpo.3-amd64 #1 SMP Debian 4.9.30-2+deb9u5~bpo8+1 (2017-09-28) x86_64 GNU/Linux
````
I had quite a bit of trouble with the speed of the luna editor, but almost everything else on my system is fast.
````
$ free -h
             total       used       free     shared    buffers     cached
Mem:          7.7G       6.5G       1.2G       344M        28K       2.4G
-/+ buffers/cache:       4.1G       3.6G
Swap:         7.9G       2.3G       5.6G
````

````
$  cat /proc/cpuinfo 
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 61
model name	: Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz
stepping	: 4
microcode	: 0x25
cpu MHz		: 2183.886
cache size	: 3072 KB
physical id	: 0
siblings	: 4
core id		: 0
cpu cores	: 2
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 20
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch epb intel_pt tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid rdseed adx smap xsaveopt dtherm ida arat pln pts
bugs		:
bogomips	: 4389.71
clflush size	: 64
cache_alignment	: 64
address sizes	: 39 bits physical, 48 bits virtual
power management:

processor	: 1
vendor_id	: GenuineIntel
cpu family	: 6
model		: 61
model name	: Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz
stepping	: 4
microcode	: 0x25
cpu MHz		: 2189.526
cache size	: 3072 KB
physical id	: 0
siblings	: 4
core id		: 0
cpu cores	: 2
apicid		: 1
initial apicid	: 1
fpu		: yes
fpu_exception	: yes
cpuid level	: 20
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch epb intel_pt tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid rdseed adx smap xsaveopt dtherm ida arat pln pts
bugs		:
bogomips	: 4391.14
clflush size	: 64
cache_alignment	: 64
address sizes	: 39 bits physical, 48 bits virtual
power management:

processor	: 2
vendor_id	: GenuineIntel
cpu family	: 6
model		: 61
model name	: Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz
stepping	: 4
microcode	: 0x25
cpu MHz		: 2200.402
cache size	: 3072 KB
physical id	: 0
siblings	: 4
core id		: 1
cpu cores	: 2
apicid		: 2
initial apicid	: 2
fpu		: yes
fpu_exception	: yes
cpuid level	: 20
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch epb intel_pt tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid rdseed adx smap xsaveopt dtherm ida arat pln pts
bugs		:
bogomips	: 4390.81
clflush size	: 64
cache_alignment	: 64
address sizes	: 39 bits physical, 48 bits virtual
power management:

processor	: 3
vendor_id	: GenuineIntel
cpu family	: 6
model		: 61
model name	: Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz
stepping	: 4
microcode	: 0x25
cpu MHz		: 2200.000
cache size	: 3072 KB
physical id	: 0
siblings	: 4
core id		: 1
cpu cores	: 2
apicid		: 3
initial apicid	: 3
fpu		: yes
fpu_exception	: yes
cpuid level	: 20
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch epb intel_pt tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid rdseed adx smap xsaveopt dtherm ida arat pln pts
bugs		:
bogomips	: 4390.86
clflush size	: 64
cache_alignment	: 64
address sizes	: 39 bits physical, 48 bits virtual
power management:
````

**Comment by piotrMocz** [comment]
Hey @timthelion, sorry to hear about your issues. There should be a `Download 1.0 beta` button on the main http://www.luna-lang.org/ page. See the screenshot I attached.
<img width="1222" alt="screen shot 2018-01-18 at 14 55 57" src="https://user-images.githubusercontent.com/3109645/35101465-ef50c442-fc5f-11e7-80e5-8156f6774dc9.png">
This should download a Luna Installer that you will be able to run and install Luna Studio.

Regarding the visualisations not showing: you need to give them some time. We are working hard on improving the performance, but right now it takes a while for the nodes to compile, typecheck and then interpret the result. We are sorry for this experience, it should be improved greatly in the future.

Also, any contributions are welcome -- if you happen to read through the code and spot some bottlenecks, make sure to open a PR ;)

**Comment by timthelion** [comment]
I'm seeing a different version of the website apparently. 

![website](https://user-images.githubusercontent.com/1391608/35102024-f4717898-fc61-11e7-9fa0-874142f7ba71.gif)

It appears that if I set the zoom level to 90%, I get a download link.

**Comment by piotrMocz** [comment]
@timthelion that's a different version indeed -- I think you're getting the mobile website (which shouldn't be missing the download link either way).

While we try to get that sorted, you can use the [direct link to the installer.](http://packages.luna-lang.org/linux/lunaInstaller.zip).

Sorry for any inconvenience!

**Comment by timthelion** [comment]
How long should I wait? I left a screen-cast running while talking to my wife and in 15 minutes the visualization still didn't appear: http://ipfs.hobbs.cz/ipfs/QmR39JXuvCQch5RvW34fKpvjVvWFi6uqaGwVi1FYYNRoFs

**Comment by wdanilo** [comment]
@timthelion There are so many things just wrong on your screencast, that I just don't know what happened. I have never seen something like that. Some of them:

1. Luna does not start properly, you have to run it couple of times (Did anyone have similar issue?)
2. The colors and shapes of elements (e.g. buttons) in the GUI are wrong
3. The Luna logo in GUI is clipped on top
4. The lines in node editor are going to wrong places - sometimes they are just to high or to low, or they just cross input/output ports instead of stop there.
5. When panning, the lines and nodes are not synchronised and flicker.
6. The visualisations do not load
7. There are no shadows below some elements
8. There is 1 or 2 px space between breadcrumb and the border of node editor
9. the MMB does not work

Oh my god, what is happening here?

This is really strange and I don't know what to do with it. @timthelion Do you have any other computer you can test it on? Because it seems like something really wrong and I don't know if we should dedicate our whole team to fight it if these issues appear only on one computer :(

**Comment by timthelion** [comment]
So I tried on my wifes laptop and the visualizations do appear (eventually), but edge drawing in the tutorial is still broken and the first time I ran luna-studio it froze:
http://ipfs.hobbs.cz/ipfs/QmSbuyPbjv394wh8c21H8aGRc2SsY7frbPVCowaizowVRo
http://ipfs.hobbs.cz/ipfs/QmPoyjfdfNxik1yJAMvzCM3ieb5pJCYMAWSdrEXKLW1YnA

I deleted the ~/.luna folder on my laptop and installed again and now the visualizations do appear (eventually) and it appears that luna-studio starts up reliably.

http://ipfs.hobbs.cz/ipfs/QmSH3LEc9A7bThKG7Xiddsy2tpdePzpVkNPyuAu1tEijE5

**Comment by wdanilo** [comment]
@timthelion Have you tried the 1.0.1 version?

**Comment by kustosz** [comment]
These issues are fixed in newest versions. Closing for now, please reopen if something is still broken.
