### ISSUE TITLE
Node editor is slow to react to input

### ISSUE THREAD

**Issue by vladdu** [luna/luna-studio#720]
I have tested 1.0 beta on both windows and Linux. 

Displaying the different circles takes 5-6 seconds or more and in the meanwhile, the node editor doesn't work (although it looks like it is). Canceling the tutorial makes thing a little better, but not fast enough.

As an example:
- launch Luna Studio, start the basic tutorial and cancel it right away
- create a circle
- connect from radius; the input port on the new circle is only available after a few seconds
- toggle the display option for the circle
- create a new circle
- connect from innerRadius, but input port is only available after the previous circle has been displayed, which for me takes almost 10 seconds

After the first time a circle is displayed, things go smooth; maybe there are a lot of libraries being loaded the first time? When doing the same within the tutorial, it keeps being as slow for the following steps.

**Comment by wdanilo** [comment]
@vladdu I've got an idea! Could you try opening Luna and waiting couple of minutes before starting tutorial? What you experience could be the fact that after starting Luna we are typechecking and compiling all the standard libraries. We do not yet provide mechanism for caching it, so it happens everytime you start the environment, but we havent observed that it affects the gui interactivity so strongly. We are right now focusing on second release, which will be performance-oriented release and will include caching mechanism.

**Comment by vladdu** [comment]
It looks like that doesn't help. Actually, if I start a new project (right away after launch) and do something similar to the tutorial, it works as expected. Almost: displaying the value of the 'circle' object still takes a while.

If you are already doing performance improvements, perhaps this issue can wait. But if you could reproduce it, it could provide a good test case, maybe.

**Comment by wdanilo** [comment]
@vladdu We are making performance improvements on much lower level currently, but this will definitely help in some time when we will profile higher level things. We will check it out. Thank you so much for so detailed descriptions!

**Comment by kustosz** [comment]
OK, basically @vladdu first guess correct.
Our typechecker is lazy – attempts to actually compile a function the moment it is needed for the first time. After that, the result is cached until the function is changed (which, in case of things like `circle`, means "cached forever").
That's why the first `circle` takes a long time – if you look at the source code, it actually compiles pretty much everything inside the Graphics2D  library and a chunk of Std.Base. All the uses of `circle` after that will just use the precompiled primitives and thus be significantly faster.
This is also why things like "run LunaStudio and wait for some time" don't work – Luna Studio won't attempt to compile anything until it really is needed.

**Comment by vladdu** [comment]
Ok, so wouldn't it make sense to have at the very least Std.Base precompiled (maybe as part of the installation), and also have the cache live over several sessions?

**Comment by kustosz** [comment]
It does make sense definitely and we're working on it. Currently though our intermediate representation (which is how the program is represented in memory) does not serialize to hard drive that good. It's a big omission, but will be solved as part of our current typechecking performance improvement efforts.

**Comment by qwoz** [comment]
I've encountered the same performance issues. I'm using 64-bit Windows 7 Professional. Everything takes forever to respond and at some points in the tutorial when the tutorial displays "Viewing the results. Please wait..." I have to wait approximately 1 minute and all 8 cores of my machine get pegged at 100% CPU. This seems to happen almost always if I perform the steps manually. It happens less frequently if I blindly click "Next" in the tutorial bubble.

Not sure if this is at all related, but every time I enable visualization via the "eye" icon (whether I do this manually or allow the tutorial to do it for me) the only thing I see is:
```
Object
  > definition: Object
  > transformation: Array[6]
```
Written below the various nodes. My clue that this wasn't normal was that the tutorial displayed the message "Oh no! It seems like our logo has incorrect rotation. Let's fix that!" and I found myself wondering "Logo? What logo?".

**Comment by dmorehouse** [comment]
I am also having this issue.  After playing with both in the tutorial and outside of it, it seems like it's the use of logoBody that really slows things down.  Everything up to that point is quick-ish.  Screen responds in sub-second and I can add a circle in a few seconds.  However, once I use logoBody either on the screen or my main function (same thing right), after each change it takes 10-15 seconds with my CPU pegged before a new node's eye shows up after I add it.

**Comment by fargolo** [comment]
I am getting the same here.

How "much" hardware do you need for a good user experience with Luna-studio?
I'm running Intel(R) Core(TM) i7-4510U CPU @ 2.00GHz ; 16 GB RAM.

Couldn't you quick fix it with an option to save compiled binaries to the hard drive?

**Comment by wdanilo** [comment]
@fargolo bad news is that you need really buffy machine currently. Good news is that this week we've released a new internal Luna 2.0 preview release which works really fast on average laptops, so really soon you should get a big update! We've been working on it for the last 5 months and the main focus point was exactly the performance.

**Comment by fargolo** [comment]
@wdanilo Wow! That is good news :)

**Comment by sylwiabr** [comment]
@fargolo so the new package 1.4 with faster core is here. The GUI update is coming :)

**Comment by fargolo** [comment]
@sylwiabr I noticed significant improvements. I would need two screens right now in order to edit code and play with the nodes at the same time. 

I see some real potential here. Is there anyone working on an integration with R?
I might contribute. There is HaskellR. https://tweag.github.io/HaskellR/

**Comment by wdanilo** [comment]
@fargolo I'd love to chat more about it. We've got plans to integrate Python and R as soon as possible and we've got a rough plan hoe we can do it step by step. Any help here would be more than appreciated, so I'd love to have you on board. Moreover I'd love to know more about what you would like to use Luna for. Please contact me (login "wdanilo") on our discord chat - you can write in general and just mention me there.

**Comment by wdanilo** [comment]
Since we've got Luna 1.4 released I will close this issue. Please feel free to re-open if anyone will encounter any slowdown regarding our interface. Please keep also in mind that big GUI refresh is coming soon with Luna 2.0 making the node interface much more fluent. The new type-checking engine (faster backend) however, is already there.
