### ISSUE TITLE
Tutorials list never loads

### ISSUE THREAD

**Issue by duncancarroll** [luna/luna-studio#723]
Version: 1.18.0
Platform: Windows 10

Never loads:

![tutorials-list](https://user-images.githubusercontent.com/812800/35107643-5d8cbd10-fc26-11e7-91b8-7b5fd9c998e4.JPG)

**Comment by pmlodawski** [comment]
Hello @duncancarroll, thank you for your bug report!

This problem has already been solved (#684). Please try out nightly version `1.0.1 BETA`. It is available in drop down menu in `lunaInstaller`

**Comment by duncancarroll** [comment]
Great, I'll give it a try--thanks!
