### ISSUE TITLE
cannot explore upstream in the dataflow

### ISSUE THREAD

**Issue by timthelion** [luna/luna-studio#727]
![foo](https://user-images.githubusercontent.com/1391608/35113046-6f735188-fc80-11e7-9df9-669748127667.gif)

I'd like to be able to explore upstream in the dataflow. For example, if I select the argument of type "Text" which is passed to "readFile" I should be exploring for functions/values of type "Text" or functions who's return value is text such as "a → b → Text". I would then be able to build upwards from there.

**Comment by wdanilo** [comment]
Thanks for posting it! Duplicate: https://github.com/luna/luna-studio/issues/725
