### ISSUE TITLE
 Updating the embedded Atom

### ISSUE THREAD

**Issue by wdanilo** [luna/luna-studio#730]
Source: https://discuss.luna-lang.org/t/updating-the-embedded-atom/105

"I installed version nightly 1.0.1 (using the graphical installer) on Windows 10 and, in looking around, I found a settings option to allow Atom to update. I checked that, and in the packages section a bunch of the packages showed updates as being available. I allowed these to be done and after several had downloaded, there was a restart prompt saying that the rest of the packages would be completed afterwards. I restarted, but unfortunately Luna Studio was now broken.

If it’s currently unsafe to allow updates, maybe the option should be disabled so that others don’t end up with a broken environment. If it should be OK to get the updates in principle, can you just confirm that something is currently broken in the particular build I had?"

**Comment by wdanilo** [comment]
@sylwiabr I need your help here. Should we disallow Atom updates. If so, I completely don't remember the reason for it, could you please remind me?

**Comment by piotrMocz** [comment]
Be advised that this is a cumbersome task that has proven to be really difficult. @pmlodawski could you elaborate on what went wrong?

**Comment by pmlodawski** [comment]
We are not compatible with newer atom, there are plenty of api changes. We should disallow updating
