### ISSUE TITLE
"Data.Vector.Mutable: uninitialized element" and freeze

### ISSUE THREAD

**Issue by rpglover64** [luna/luna-studio#731]
Trying to do the tutorial, I got to scrolling around a real number slider to rotate the Luna logo. Then I got this error, and nothing I clicked on changed the screen:
![screen shot 2018-01-18 at 10 26 52 am](https://user-images.githubusercontent.com/233689/35133660-42460e7a-fc86-11e7-9080-851c4ae73ba4.png)

I couldn't even copy and paste the error message.

**Comment by wdanilo** [comment]
Are you able to reproduce this bug? If so, could you please describe exact conditions when it happens?

**Comment by rpglover64** [comment]
I can try again tomorrow, but I doubt it. It was on a Mac when when I was
rapidly moving the slider back and forth.

**Comment by wdanilo** [comment]
Please try. Without reproducible guide it is insanely hard to track it :(

**Comment by rpglover64** [comment]
Could not reproduce. Seems to have been a one-off bug. I might consider
liberally sprinkling HasCallStack. It also seems like crash handling (or
recovery) code could help, so that if an ErrorCall occurs, the whole
application doesn't freeze up.

Either way, this issue should probably be closed.

**Comment by wdanilo** [comment]
@rpglover64 right! In case of such erros we sohuld recover from them automatically by restarting backend. I've created issue for it: https://github.com/luna/luna-studio/issues/740

**Comment by pmlodawski** [comment]
@wdanilo please see #454
