### ISSUE TITLE
Cannot read property 'numerator' of undefined

### ISSUE THREAD

**Issue by raymestalez** [luna/luna-studio#732]
I'm getting this error when I launch luna 1.0.1 nightly:

![image](https://user-images.githubusercontent.com/4761235/35144057-418403a2-fcb8-11e7-94e8-ae5ee4839fe5.png)

**Comment by raymestalez** [comment]
I see the error after opening it.

**Comment by raymestalez** [comment]
Huh, interesting. I've just tried reproducing it and couldn't, no error anymore...
Maybe it was compiling something after the installation and didn't finish?

**Comment by wdanilo** [comment]
I dont know. It is a very strange looking error. I will close it, because it is not reproducible and you were the only one who actually had it. Happy it works! If you ever get it again, please reopen :)
