### ISSUE TITLE
Basics tutorial doesn't work on Windows 10

### ISSUE THREAD

**Issue by ricksanchez** [luna/luna-studio#737]
I just installed the Luna 1.0

I clicked in the BasicstTutorial
Click next, next, until I was requested to write circle and button "down" and enter
the circle node was not created and the "tab" menu is still displayed but it doesn't respond to esc/enter
the current text in the text bubble is "Click on the output port of the radius....", but at this point I cannot longer interact with the editor.
When I click next, a line from the node to the cursor appears and in the bubble "connecting the nodes, please wait...." and got stuck forever (until I click X and the tutorial finished).

**Comment by crawfordcomeaux** [comment]
I have this same issue on Ubuntu 14.04. Should I open another issue for this?

**Comment by wdanilo** [comment]
@crawfordcomeaux, no - it is related. However, please do provide your system info!

**Comment by crawfordcomeaux** [comment]
Would you be willing to give me a set of commands to generate the info you'd like?

**Comment by crawfordcomeaux** [comment]
My issue is different. The tutorial's really slow to respond, spending minutes at "please wait," typically at "Viewing the results" steps.

**Comment by wdanilo** [comment]
crawfordcomeaux , sure, lets check it out! Please execute it when running Luna Studio and tutorials:
```less /proc/cpuinfo
free -mh
```
Moreover, what is your cpu usage when you observe the slowdown? Does it run faster if you wait for a while? Im asking it because Luna currently compiles stdlib in yhe background everytime you start it.

**Comment by cguebert** [comment]
I have a similar issue, the circle node is never created, even if I click on the 'next' button. The tutorial is then in a dead end, and as all actions are blocked in the tutorial, I cannot progress.

**Comment by ricardopieper** [comment]
Same problem: then I create the node, the tutorial asks me: Click on the output port of the radius.... but I can't do that.

**Comment by Gurkenglas** [comment]
Here's a video reproducing this. https://streamable.com/eocf5

**Comment by kustosz** [comment]
There is a workaround in the tutorial scenario for this. If you run the tutorial again (no need to update or anything, just select it again on the dashboard). Keeping this issue open for now, as the root is not solved yet, but you should all be able to use the tutorial.
