### ISSUE TITLE
luna-empire.exe is still opened after Luna Studio was closed

### ISSUE THREAD

**Issue by ricksanchez** [luna/luna-studio#738]
The luna-empire.exe process is still in the task manager
and when I close it, it is respawned for no good reason.

**Comment by mottosso** [comment]
Getting this too. There is a Service by the same name that you can stop.

**Comment by wdanilo** [comment]
We know that it happens on Windows. Sorry for that. Windows support still needs some love and we are working to improve it! As I understand, it doesnt do any harm to you guys at the moment and it's not critical?

**Comment by ricksanchez** [comment]
It is a feature, not a bug, today I noticed that the Luna added **4** Windows services, and that is why it respawns. Maybe this is not good, I don't want to spend resources of my PC for this when Luna is not used.

Is there some uninstaller to remove those services? :)

**Comment by wdanilo** [comment]
@ricksanchez We are already searching for running them only when Luna Studio will start. We assumed (incorrectly) that it is not possible on Windows. @pmlodawski will provide detailed information about it.

**Comment by kustosz** [comment]
@ricksanchez @mottosso Sorry for the issue. If you update Luna to the nightly version 1.0.2 (available in the Luna Installer), the services will stop and be spawned only while Luna Studio runs.
