### ISSUE TITLE
When backend error occurs, we should recover from it automatically.

### ISSUE THREAD

**Issue by wdanilo** [luna/luna-studio#740]
Related (read comments): https://github.com/luna/luna-studio/issues/731#issuecomment-359068699

**Comment by mikusp** [comment]
Every backend service is automatically restarted bu supervisord/Windows. It's likely that GUI has to handle this situation more gracefully

**Comment by wdanilo** [comment]
@mikusp thanks! So how should we change the topic of this bug to describe the issue in the best way?

**Comment by mikusp** [comment]
Tracked in #870
