### ISSUE TITLE
Copy-pasting from text representation also copies node metadata outside the editor

### ISSUE THREAD

**Issue by ricardopieper** [luna/luna-studio#744]
On windows, I select a function's text on the text editor:

![image](https://user-images.githubusercontent.com/4030858/35185273-ebe2661e-fde8-11e7-88fa-436c05734c38.png)

And I press `CTRL + C`.

This is what `CTRL+V` does outside Luna Studio:

```
«6»«7»def multiply term1 term2:
    «8»product = term1 * term2
    product
### META {"metas":[{"marker":8,"meta":{"_displayResult":false,"_selectedVisualizer":null,"_position":{"fromPosition":{"_vector2_y":0,"_vector2_x":0}}}}]}
```

If I copy the text inside Luna Studio, everything goes well.

I know that Skype has a similar feature: If you copy another person's text, and then you paste it inside Skype, you'll be creating a quote. However, if you paste it outside Skype, only the selected text will be copied.

**Comment by wdanilo** [comment]
Actually we designed it this way intentionally, so if you copy and send the code to your friend and he use paste, he will get nodes aligned the same way you have! I belive we allow for `ctrl + shift + c` shortcut which will not copy metadata. I'll close this issue for now, but please feel free to provide your feedback and thoughts on it!
