### ISSUE TITLE
The "CryptoCurrencyPlayground" and "BasicsTutorial" projects need two clicks to open

### ISSUE THREAD

**Issue by gelisam** [luna/luna-studio#748]
Repro steps:

1. Restart LunaStudio
2. Click one either the "CryptoCurrencyPlayground" or the "BasicsTutorial" project to open it.

Observed: The project's preview turns into a Luna spinner, but the project never loads (I waited 5 minutes)

![screen shot 2018-01-21 at 11 37 13 am](https://user-images.githubusercontent.com/49000/35196921-9ca4a17a-fea6-11e7-91e3-096e211932f8.png)

Expected: The Luna spinner spins for a bit, then the project opens.

Workaround: Click the project a second time.

I've tried all four tutorial projects several times, this never occurs with "USElectionPlayground" nor "TramsPlaygroud", and it always occurs with "CryptoCurrencyPlayground" and "BasicsTutorial".

**Comment by wdanilo** [comment]
@gelisam I cannot reproduce it. Does it happen every time? Have you observed any correlation between this behavior and anything else? Moreover, are you using the 1.0.1 version?

**Comment by gelisam** [comment]
> Does it happen every time?

After restarting LunaStudio, yes. Otherwise the behaviour is inconsistent.

> Moreover, are you using the 1.0.1 version?

I think so, is there any way to check? I installed 1.0 first, then I switched to 1.0.1 before I started to report the bugs, but the UI looks identical and the About page gives Atom's version number, not LunaStudio's.

**Comment by gelisam** [comment]
Ah, I finally found a place where the version number is written: when clicking on the gear icon to list the settings, a message says `Package are published to atom.io and are installed to /Users/gelisam/.luna/config/luna-studio/1.0.1/atom/packages`

**Comment by gelisam** [comment]
I'm on macOS, so I don't have a `.luna/bin/luna-studio/` folder, but I did find a `/Applications/LunaStudio.app/Contents/Resources/current/config/version.txt` which contains `1.0.1`.

**Comment by gelisam** [comment]
About the bug's reproducibility: maybe it's a timing issue? I'm guessing that my computer must be much slower than the ones you're testing with, because on my machine, Luna doesn't have the fast feedback loop this kind of app usually aims for. For example, when I finish the BasicsTutorial and play with the rotation amount, it takes a good ~11 seconds for the rotated Luna logo to update. I have a 1.7 GHz Intel Core i7.

**Comment by wdanilo** [comment]
@gelisam I believe that Luna 2.0 we are working on (codename "performance release") will work smoothly on your machine too. We are doing really a lot of work behind the scenes (like compiling std library every time you start Luna Studio or use new functions) and we havent included many optimizations (like compiled libraries cache yet). It will change!

**Comment by kustosz** [comment]
That has nothing to do with Luna performance, it's GitHub choking when downloading the tutorial zip. @pmlodawski probably tweaking request headers (timeouts) may help with this one.

**Comment by pmlodawski** [comment]
@gelisam thanks for pointing that only these two tutorials caused this error. It was much easier to debug it.

After investigation it looks like issue in `unzip` package which we are using https://github.com/EvanOxfeld/node-unzip/issues/80 . Switching to its fork,  https://github.com/ZJONSSON/node-unzipper which have this issue solved may help
