### ISSUE TITLE
"API rate limit exceeded" when creating repro steps

### ISSUE THREAD

**Issue by gelisam** [luna/luna-studio#749]
I am trying to help by reporting the bugs I am encountering while trying out LunaStudio. Since the application seems to keep a lot of state in the background and this affects the behaviour of the bugs, I have been restarting the application repeatedly in order to make sure my repro steps are repeatable from a blank state. But now I get the following message when I start LunaStudio:

"Cannot download tutorial list. API rate limit exceeded for [my IP address]. (But here's the good news: Authenticated requests get a higher rate. Check out the documentation for more details.)"

![rate-limit](https://user-images.githubusercontent.com/49000/35197152-87e9f41c-fea9-11e7-87cb-dc8f70073e21.png)

The "documentation" button brings me to the [Luna User Guide](https://luna-lang.gitbooks.io/docs/content/), which does not mention "Authenticated requests", so I suspect this is a message from a service LunaStudio is using rather than a message from LunaStudio itself.

Also, why is an API call required to get a list of tutorials? Shouldn't they get installed on my machine during the installation?

**Comment by wdanilo** [comment]
@gelisam thank you so much for your help and reporting the issues! It helps us much make Luna better every day!

I have never seen this error. I'm sure @pmlodawski will help here.

**Comment by kustosz** [comment]
This is GitHub defending against DDoSing them – we use their API to get the list of tutorials and their API limits for unauthorized requests are terrible (and when we tried to authorize them it ended up in locking our keys).
We may want to consider caching the list to display when such errors happen.

**Comment by pmlodawski** [comment]
@kustosz it may be a good idea
