### ISSUE TITLE
BasicsTutorial's "viewing circle2" and "viewing logoBody1" steps do nothing

### ISSUE THREAD

**Issue by gelisam** [luna/luna-studio#751]
When following the BasicsTutorial, there is a step which says "Let's see what happened so far. Click the eye icon of the `circle2` node, to show the visualization." While doing so for `circle1` worked just fine, doing so for `circle2` moves on to the next step without displaying the second circle:

![circle2-not-shown](https://user-images.githubusercontent.com/49000/35197701-29bb50ae-feb1-11e7-8e4c-5db814d63aff.png)

Same thing after clicking the eye for `logoBody1`:

![logobody1-not-shown](https://user-images.githubusercontent.com/49000/35197738-090cb0cc-feb2-11e7-8cd3-c981aea14458.png)

**Comment by gelisam** [comment]
Work around: close or finish the tutorial then click on the eye again.

**Comment by wdanilo** [comment]
@gelisam hmm, seems like a tutorial workflow bug. Thanks for reporting! @pmlodawski, @ljkania  could you please look at it?

**Comment by kustosz** [comment]
Should be fixed in newest versions, closing. Please reopen if the issue manifests itself again.
