### ISSUE TITLE
Cryptocurrency edge selection

### ISSUE THREAD

**Issue by Gurkenglas** [luna/luna-studio#757]
On the Cryptocurrency playground, I did something involving clicking on the left half of the edge connecting the upper node to the right node, resulting in:

https://i.gyazo.com/cd737f315c54292396ea57d927262f69.png
![image](https://user-images.githubusercontent.com/1489801/35198378-47f12aa2-feee-11e7-9cfd-d7d828670d92.png)

Clipboard contents:

Breadcrumb {_items = [Definition {_nodeId = a535d5c6-1c3c-4696-bcea-a1fa8021ff14}]}

while processing event

empire.graph.disconnect.response

======= logs: =======

=== s-luna-empire.wrapper.log ===
2018-01-20 02:14:39,084 INFO  - Starting ServiceWrapper in the CLI mode
2018-01-20 02:14:52,881 INFO  - Completed. Exit code is 0
2018-01-20 02:14:55,723 INFO  - Starting ServiceWrapper in the CLI mode
2018-01-20 02:14:56,567 INFO  - Completed. Exit code is 0

**Comment by wdanilo** [comment]
@Gurkenglas thank you fro reporting the issue with a screenshot! Are you able to reproduce this error? If so, could you describe step by step how you get it?

**Comment by Gurkenglas** [comment]
I've made a video fishing for issues on the Cryptocurrency Playground and am not sure whether I should be reporting an issue for every bump I hit. You can watch my troubles and tell me what you think. https://streamable.com/v8pys

**Comment by pmlodawski** [comment]
I tried to reproduce it too, but with no luck. Feel free to reopen this issue if you find a way to reproduce it.
