### ISSUE TITLE
Windows installer doesn't create system entry

### ISSUE THREAD

**Issue by ShynRou** [luna/luna-studio#762]
Windows installer doesn't create application entry and can not be automaticly uninstalled.
You have to manually stop (and optionally remove) all services: 
- luna-empire
- broker
- redo-undo
- ws-connector

and delete all files.

And as a sidenote: The IDE barely worked and was super slow. I will check back when it's further into development.

**Comment by kustosz** [comment]
We're working on the uninstallers, expect these soon. The progress is tracked inside https://github.com/luna/luna-manager/issues/115
