### ISSUE TITLE
Luna Start-up Issues 1.0.2...

### ISSUE THREAD

**Issue by SalvorinFex** [luna/luna-studio#769]
On starting the Beta 1.0.2 that fixed the `luna-emapire.exe` bug, I receive the following 2 reports.

[Luna 102 start-up.txt](https://github.com/luna/luna-studio/files/1657932/Luna.102.start-up.txt)

AND...
Connection closed.

======= logs: =======

=== s-luna-empire.wrapper.log ===
2018-01-16 15:14:47,304 INFO  - Starting ServiceWrapper in the CLI mode
2018-01-16 15:14:51,138 INFO  - Completed. Exit code is 0
2018-01-16 15:14:55,839 INFO  - Starting ServiceWrapper in the CLI mode
2018-01-16 15:14:56,582 INFO  - Completed. Exit code is 0

As well as the `Fetching Tutorials` is stuck again, none show up.
After about 5 mins still none in there.

**Comment by kustosz** [comment]
The log indicates that this comes from the `1.0` version (it sits in this line: `At C:\Users\kroesener\.luna\config\luna-studio\1.0\atom\packages\luna-studio\lib\projects.coffee:160`).
Are you sure you have selected the right version when installing (you need to select it under `nightly` in the installer)? Did the installation exit without any errors? If so, that would mean there's a bug with our update process.
For basic diagnostics, please check the following:
1. If there's a `1.0.2` directory inside `C:\Program Files\LunaStudio`
2. Where does the `C:\Program Files\LunaStudio\current` shortcut point to (should point to the `1.0.2` directory mentioned above)
If the structure described in 1. and 2. is correct, please remove the `.luna` directory in your home dir and start Luna Studio again.
If there's something wrong with that structure, please try running the installer again and let us know whether that fixes things.

**Comment by SalvorinFex** [comment]
Sorry for this, I was using the older shortcut, as I thought that it would get updated as well.
