### ISSUE TITLE
Some videos of my experience on Windows 10

### ISSUE THREAD

**Issue by ricardopieper** [luna/luna-studio#771]
Those videos are unlisted, and mostly they cover the basic tutorial, which is working, although I, being kind of clumsy when I type or move the mouse, found it kinda hard to complete. I know it can be infuriating watching me doing things so slowly, but there's not much I can do about that.

https://youtu.be/_fD_k4lLwKk: In this video, I was asked to enter "circle1 + circle2", but instead I was lazy and tried "circle1+circle2" (with no whitespace). The tutorial stopped working then, and didnt accept my expression.

https://youtu.be/VhaSBxScaQw: Apparently the order and positioning of the nodes are super important. I thought Luna would try to add the code to the function by analyzing which are the dependent nodes, and add the source text in the adequate position, regardless of the X Y position. If that's a design decision, I don't get why. If I do the same thing in the correct order and positioning, things work fine and I can move whatever around.

https://youtu.be/2S-vfbYmpiM: I forgot to press the down arrow key and although it yielded the same result, the tutorial blocked. I'm not against forcing me to do it correctly (pressing arrow down), but it shouldn't break the tutorial there. Although I thing there are already issues for that.

https://youtu.be/Bp_dds9QDUU (still uploading ATM): This is one where I actually managed to complete the tutorial after many retries. I wished the tutorial could cover more of the graphical notation, but it's a good start.

Feel free to close the issue if none of this is releavant or if those are known issues/design decisions!

**Comment by kustosz** [comment]
@ricardopieper thank you for the videos, they are all relevant!

The first and the third one are connected to #737 – we have a system in place to prevent accidentally-breaking actions, but it got overzealous on Windows 10 and I had to temporarily disable some parts (namely those connected with validating keyboard actions) – @ljkania is working on it right now.

The second issue is a lack of feature – for now the node's position in code is connected to the `X` coordinate. This is a temporary measure, and we're working on changing that – e.g. if you connect a node from further down in code to one before it, they will get reordered like you'd expect. We still need to reorder them based on the expression alone, but that should be coming to Luna soon. For now, unfortunately, there are still scenarios when the order does matter.

Your last video does not look like you completed it – it looks like you've run into the same issue as in the third.

Sorry for all the issues, there's something strange with how Atom handles events on Windows and it is unfortunately easy to break it. The fixes should be in place soon.

**Comment by ricardopieper** [comment]
Oh, I may have uploaded the wrong file in the last video! But I managed to complete it. I removed the video link from the original post.

Since those issues have already been mapped out, I'll close the issue here. 

Good luck guys, I'm looking forward for this project! I'll try to use Luna more "seriously" very soon.
