### ISSUE TITLE
"Fatal error" on MacOS

### ISSUE THREAD

**Issue by csi-adziahel** [luna/luna-studio#789]
Repro: 

1. start freshly installed Luna Studio (v 1.0.2-nightly)
2. wait a bit

What happens: an error message pops up (behind project selector)

```
Connection closed.
```

<details><summary><code>======= logs: =======</code></summary>

```
=== luna-empire-stdout---supervisor-m3LFBK.log ===
DEBUG Loading Luna configuration
DEBUG Loading Luna configuration
DEBUG Connecting to bus...
DEBUG Connected to bus
INFO Subscribing to topics: ["empire."]
INFO BusEndPoints
  { controlEndPoint = "tcp://127.0.0.1:30530"
  , pullEndPoint = "tcp://127.0.0.1:30531"
  , pubEndPoint = "tcp://127.0.0.1:30532"
  }
DEBUG Loading Luna configuration
DEBUG Connecting to bus...
DEBUG Connecting to bus...
DEBUG Connecting to bus...
DEBUG Connecting to bus...
DEBUG Connected to bus
DEBUG Connected to bus
DEBUG Connected to bus
DEBUG Connected to bus
```

</details>

**Comment by kustosz** [comment]
@mikusp @sylwiabr this looks like your area of expertise. What can we do to debug this?

**Comment by csi-adziahel** [comment]
I'm willing to provide additional data, should you need any

**Comment by sylwiabr** [comment]
Could you please send zipped `~/.luna/logs` folder?

**Comment by csi-adziahel** [comment]
@sylwiabr [logs.zip](https://github.com/luna/luna-studio/files/1710598/logs.zip)

**Comment by sylwiabr** [comment]
Ok, I can see. We are using port 8088 for one of our services which is already in use. Thank you for your report, we will change it in the next version. Sorry for inconvenience.
