### ISSUE TITLE
Windows installation: Slow installation / no progress bar on installation.

### ISSUE THREAD

**Issue by CaiusTSM** [luna/luna-studio#794]
Hello, I was installing Luna studio on my windows 7 64 bit machine with the command line installer. The download had a progress bar, but the installation did not. Due to the long installation time I thought it was stuck. I believe a progress bar and maybe an animation loop "[.  ]", "[.. ]", "[...]", (animated with \r and printing over it) would be great.

visual:
[...] [======>               ]  30%

**Comment by wdanilo** [comment]
I think we should also provide more interactive experience here - cleaning the screen after each question would also be great. Such indicator should also provide short info waht is going on atm, for example "extracting files".

**Comment by sylwiabr** [comment]
There is an issue in luna-manager (where it should be) for this https://github.com/luna/luna-manager/issues/130. Closing as duplicate.
