### ISSUE TITLE
Node searcher should suggest the methods based on the type of the selected node

### ISSUE THREAD

**Issue by piotrMocz** [luna/luna-studio#841]
https://cdn.discordapp.com/attachments/401739816108163073/417628671843631105/Screenshot_2018-02-26_05-26-20.png

The problem here is that after selecting the `tail1` node and hitting Tab, the Searcher displays suggestions for the `List` class, instead of `Maybe` (which is the return type of tail). This leads to the error visible in the screenshot.

**Comment by ljkania** [comment]
This issue does not exist as we discussed at luna chat. Closing.
