### ISSUE TITLE
Visualization not working in tutorial

### ISSUE THREAD

**Issue by yann-achard** [luna/luna-studio#846]
Hello, this what I get after clicking the eye icon in the tutorial. I'm guessing it should show a drawing instead.

![image](https://user-images.githubusercontent.com/1549079/36768502-67c626ca-1bf4-11e8-8aad-bd4a5ea42c5f.png)

I'm running on Windows 10.
I downloaded the tutorial data from https://github.com/luna-packages.

**Comment by AnthonyJacob** [comment]
#847 

Try to mouse over the white triangle on the left and choose different visualization.

**Comment by yann-achard** [comment]
Ah, thank you!
