### ISSUE TITLE
Editing node name and expression

### ISSUE THREAD

**Issue by kustosz** [luna/luna-studio#891]

**Comment by ljkania** [comment]
What is this issue?

**Comment by piotrMocz** [comment]
@ljkania it's about being able to edit the node's expression and name (double click, bring up the searcher, enter something and accept).

This was done, but there's a regression: the components don't have all the necessary CSS classes assigned, which in turn causes the keymaps to capture the wrong events. It's a fairly simple fix, but I'm moving this back to `In Progress`.

I know @pmlodawski is working on rewriting the text fields, so I'll wait for him with any corrections of this one.

**Comment by piotrMocz** [comment]
This task was finished by @pmlodawski . The searcher problems persist, but the editing works.
