### ISSUE TITLE
Integrate baseGL gui with building scripts

### ISSUE THREAD

**Issue by sylwiabr** [luna/luna-studio#923]
Currently to build new GUI based on baseGL we need to run few separate commands and It should be integrated with our building scripts.

- [x] Convert the script for copying sass files to the Atom bundle (`update_statics.sh`) to Python
- [x] Add this script to `build_luna`
- [x] Make the basegl gui start automatically on Atom startup (`install();`)
- [x] Possibly: remove the old GUI.

**Comment by piotrMocz** [comment]
3/4 done in the PR https://github.com/luna/luna-studio/pull/959
I still need @pmlodawski 's help switching the old gui off -- I don't know it well enough to disable it gracefully without stopping the flow of events. That has to wait till tomorrow.

**Comment by piotrMocz** [comment]
This task is finished but will not be merged into `basegl` for now. We want to keep experimenting with both GUIs open. At the same time, it is paramount that we keep testing the make-package process from time to time. To that end, we will be merging `master` into `basegl` and `basegl` into `basegl-install` and build the packages from `basegl-install`.
