### ISSUE TITLE
Build and test package with baseGL gui

### ISSUE THREAD

**Issue by sylwiabr** [luna/luna-studio#924]
Since there were no tests of the new upcoming gui on Windows and no packages were produced to test it we should check it ASAP to avoid problems later.

**Comment by lgawlik** [comment]
Tested on Windows (10) and Mac (10.13), Fedora 27, Ubuntu 14.04, 16.04
To be done:
- other Linuxes:
    - older Fedoras
    - Ubuntu 18.04
    - OpenSUSE
    - Mint
    - CentOS(es)
    - Gentoo?
- older MacOS-es:
    - 10.11
    - 10.12
