### ISSUE TITLE
using empty string on macOS in lookupSymbol function causes error

### ISSUE THREAD

**Issue by sylwiabr** [luna/luna-studio#928]
On MacOS it has to get "c++" instead of ""

**Comment by mikusp** [comment]
It got overlooked during code review, but here https://github.com/luna/luna/pull/213/files#diff-aaffaf9eee0b55d27a22e09b0e15a95bR43 it would be better to use #error directive. Other than that, it's great

**Comment by sylwiabr** [comment]
@piotrMocz confirmed it is working
