### ISSUE TITLE
Breadcrumb Error

### ISSUE THREAD

**Issue by lgawlik** [luna/luna-studio#934]
Breadcrumb {_items = [Definition {_nodeId = 573dff3a-45f8-44c2-8513-a9eb1e1862ce}]}

while processing event

empire.graph.node.updateMeta.response

======= logs: =======

=== luna-empire-stdout---supervisor-8tk2R_.log ===
(                 0.0                 0.0                 1.0                 0.0 )
(  293.73076923076917 -360.19230769230757                 0.0                 1.0 )
, _logicalToScreen = (               0.26                0.0                0.0                0.0 )
(                0.0               0.26                0.0                0.0 )
(                0.0                0.0                1.0                0.0 )
( -76.36999999999999  93.64999999999998                0.0                1.0 )
, _lastInverse = 0}}}
INFO 2018-06-07T07:49:34.800353Z	:: sending ok for empire.graph.saveSettings.request
INFO 2018-06-07T07:49:34.800801Z	:: received empire.graph.saveSettings.response
INFO 2018-06-07T07:49:49.112008Z	:: received empire.graph.collaboration.update
INFO 2018-06-07T07:50:02.488193Z	:: received empire.graph.collaboration.update
INFO 2018-06-07T07:50:05.900627Z	:: received empire.graph.collaboration.update
INFO 2018-06-07T07:50:13.874737Z	:: received empire.graph.collaboration.update
INFO 2018-06-07T07:50:13.875667Z	:: received empire.graph.collaboration.update
INFO 2018-06-07T07:50:16.806388Z	:: received empire.graph.node.updateMeta.request
INFO empire.graph.node.updateMeta.request: Request {_location = GraphLocation {_filePath = "/tmp/luna28353/tutorials/USElectionPlayground/src/Main.luna", _breadcrumb = Breadcrumb {_items = [Definition {_nodeId = 573dff3a-45f8-44c2-8513-a9eb1e1862ce}]}}, _updates = [(f8984e75-8f9f-4cb3-b67d-c2618244acf6,NodeMeta {_position = Position {fromPosition = Vector2 {_vector2_x = -208.0, _vector2_y = -208.0}}, _displayResult = True, _selectedVisualizer = Just ("LunaVisualizer: base: json","base/json/json.html")})]}
INFO 2018-06-07T07:50:17.226072Z	:: sending response for empire.graph.node.updateMeta.request
INFO 2018-06-07T07:50:17.226072Z	:: Result {_removedNodes = [], _removedConnections = [], _graphUpdates = Right (Graph {_nodes = [ExpressionNode {_exprNodeId = f8984e75-8f9f-4cb3-b67d-c2618244acf6, _expression = "getElectionData", _isDefinition = False, _name = Just "getElectionData1", _code = "getElectionData", _inPorts = LabeledTree {_subtrees = InPorts {_self = Just (LabeledTree {_subtrees = InPorts {_self = Nothing, _head = Nothing, _args = []}, _value = Port {_portId = [Self], _name = "self", _valueType = TStar, _state = NotConnected}}), _head = Nothing, _args = []}, _value = Port {_portId = [], _name = "alias", _valueType = TStar, _state = WithDefault (Expression "getElectionData")}}, _outPorts = LabeledTree {_subtrees = OutPorts [], _value = Port {_portId = [], _name = "getElectionData1", _valueType = TStar, _state = NotConnected}}, _nodeMeta = NodeMeta {_position = Position {fromPosition = Vector2 {_vector2_x = -208.0, _vector2_y = -208.0}}, _displayResult = True, _selectedVisualizer = Just ("LunaVisualizer: base: json","base/json/json.html")}, _canEnter = False}], _connections = [], _inputSidebar = Nothing, _outputSidebar = Nothing, _monads = []})}
INFO 2018-06-07T07:50:17.229675Z	:: received empire.graph.node.updateMeta.response
INFO 2018-06-07T07:50:18.237081Z	:: received empire.graph.collaboration.update
INFO 2018-06-07T07:50:48.688529Z	:: received empire.graph.collaboration.update
INFO 2018-06-07T07:50:50.446135Z	:: received empire.graph.collaboration.update
INFO 2018-06-07T07:50:50.450927Z	:: received empire.graph.collaboration.update
INFO 2018-06-07T07:52:00.092781Z	:: received empire.graph.collaboration.update
INFO 2018-06-07T07:52:00.152474Z	:: received empire.graph.collaboration.update
INFO 2018-06-07T07:52:54.121273Z	:: received empire.graph.collaboration.update
INFO 2018-06-07T07:52:54.123839Z	:: received empire.graph.collaboration.update
INFO 2018-06-07T07:52:56.79451Z	:: received empire.graph.node.updateMeta.request
INFO empire.graph.node.updateMeta.request: Request {_location = GraphLocation {_filePath = "/tmp/luna28353/tutorials/USElectionPlayground/src/Main.luna", _breadcrumb = Breadcrumb {_items = [Definition {_nodeId = 573dff3a-45f8-44c2-8513-a9eb1e1862ce}]}}, _updates = [(75c942c3-fde4-458d-909e-12b8448c6dc9,NodeMeta {_position = Position {fromPosition = Vector2 {_vector2_x = 1232.0, _vector2_y = -992.0}}, _displayResult = True, _selectedVisualizer = Just ("LunaVisualizer: map: GeoJSON","map/geojson.html")})]}
INFO 2018-06-07T07:52:57.307202Z	:: sending response for empire.graph.node.updateMeta.request
INFO 2018-06-07T07:52:57.307202Z	:: Result {_removedNodes = [], _removedConnections = [], _graphUpdates = Right (Graph {_nodes = [ExpressionNode {_exprNodeId = 75c942c3-fde4-458d-909e-12b8448c6dc9, _expression = "GeoJSONFeatureCollection \8226", _isDefinition = False, _name = Just "geojsonfeaturecollection1", _code = "GeoJSONFeatureCollection each1", _inPorts = LabeledTree {_subtrees = InPorts {_self = Nothing, _head = Nothing, _args = [LabeledTree {_subtrees = InPorts {_self = Nothing, _head = Nothing, _args = []}, _value = Port {_portId = [Arg 0], _name = "each1", _valueType = TStar, _state = Connected}}]}, _value = Port {_portId = [], _name = "alias", _valueType = TStar, _state = WithDefault (Expression "GeoJSONFeatureCollection each1")}}, _outPorts = LabeledTree {_subtrees = OutPorts [], _value = Port {_portId = [], _name = "geojsonfeaturecollection1", _valueType = TStar, _state = NotConnected}}, _nodeMeta = NodeMeta {_position = Position {fromPosition = Vector2 {_vector2_x = 1232.0, _vector2_y = -992.0}}, _displayResult = True, _selectedVisualizer = Just ("LunaVisualizer: map: GeoJSON","map/geojson.html")}, _canEnter = False}], _connections = [], _inputSidebar = Nothing, _outputSidebar = Nothing, _monads = []})}
INFO 2018-06-07T07:52:57.311618Z	:: received empire.graph.node.updateMeta.response
INFO 2018-06-07T07:53:01.81758Z	:: received empire.atom.file.open.request
INFO 2018-06-07T07:53:03.499375Z	:: sending ok for empire.atom.file.open.request
INFO 2018-06-07T07:53:03.499718Z	:: received empire.atom.file.open.response
INFO 2018-06-07T07:53:03.51024Z	:: received empire.atom.file.get.request
INFO empire.atom.file.get.request: Request {_filePath = "/tmp/luna28353/tutorials/USElectionPlayground/src/Main.luna"}
INFO 2018-06-07T07:53:03.510674Z	:: sending response for empire.atom.file.get.request
INFO 2018-06-07T07:53:03.510674Z	:: Result {_code = "import Std.Base\nimport Std.Geo\n\ndef getElectionData:\n    path = \"data\" . addPathSegment \"us_election.json\"\n    file = readFile path\n    json = JSON.parse file\n    asObject1 = json . asObject\n    map1 = asObject1 . map .asText\n    toList1 = map1 . toList\n    toList1\n\ndef getStateGeometries:\n    path = \"data\" . addPathSegment \"states.json\"\n    readFile1 = readFile path\n    parseJSON1 = JSON.parse readFile1\n    lookup1 = parseJSON1 . getList \"features\"\n    map1 = lookup1 . each (feature: (feature . get \"properties\" . getText \"name\", feature . get \"geometry\"))\n    fromList1 = map1 . fold Map.empty ((k,v): m: m.insert k v)\n    fromList1\n\ndef makeStyle item:\n    party = item.second\n    baseStyle = JSON . empty . insert \"color\" \"white\" . insert \"opacity\" 1 . insert \"dashArray\" \"3\" . insert \"fillOpacity\" 0.7\n    democrats = party == \"D\"\n    color = if democrats then \"#0000FF\" else \"#FF0000\"\n    insert1 = baseStyle . insert \"fillColor\" color\n    insert1\n\ndef makeFeature stateGeometries item:\n    style = makeStyle item\n    geo = stateGeometries . get item.first\n    props = JSON . empty . insert \"style\" style\n    feature = GeoJSONFeature props geo\n    feature\n\ndef main:\n    getElectionData1 = getElectionData\n    stateGeometries = getStateGeometries\n    each1 = getElectionData1 . each (makeFeature stateGeometries)\n    geojsonfeaturecollection1 = GeoJSONFeatureCollection each1\n    None\n"}
INFO 2018-06-07T07:53:03.535443Z	:: received empire.atom.file.get.response
INFO 2018-06-07T07:53:03.621956Z	:: received empire.graph.saveSettings.request
INFO empire.graph.saveSettings.request: Request {_location = GraphLocation {_filePath = "/tmp/luna28353/tutorials/USElectionPlayground/src/Main.luna", _breadcrumb = Breadcrumb {_items = [Definition {_nodeId = 573dff3a-45f8-44c2-8513-a9eb1e1862ce}]}}, _settings = LocationSettings {_visMap = Just (fromList [(TCons "Text" [],("LunaVisualizer: base: text","base/text/text.html")),(TCons "GeoJSONFeatureCollection" [],("LunaVisualizer: map: GeoJSON","map/geojson.html"))]), _camera = CameraTransformation {_screenToLogical = ( 3.846153846153846               0.0               0.0               0.0 )
(               0.0 3.846153846153846               0.0               0.0 )
(               0.0               0.0               1.0               0.0 )
( 745.1667116213463 -312.496058291916               0.0               1.0 )
, _logicalToScreen = (                0.26                 0.0                 0.0                 0.0 )
(                 0.0                0.26                 0.0                 0.0 )
(                 0.0                 0.0                 1.0                 0.0 )
( -193.74334502155006   81.24897515589817                 0.0                 1.0 )
, _lastInverse = 0}}}
Requested module: Std.Base
Compiling module: Std.Base
Requested module: Std.HTTP
Compiling module: Std.HTTP
Requested module: Std.System
Compiling module: Std.System
Requested module: Std.Time
Compiling module: Std.Time
Requested module: Std.WebSockets
Compiling module: Std.WebSockets
Requested module: Std.Foreign
Requested module: Std.Foreign.C.Value
Compiling module: Std.Foreign.C.Value
Compiling module: Std.Foreign
OPEN PROJECTRequest {_requestId = 5146baed-7913-446a-be9e-630e453d129a, _guiID = Just e4abe696-5a3a-c505-511d-c232b404372f, _request = Request {_rootPath = "/tmp/luna28353/tutorials/USElectionPlayground"}}
Requested module: Std.Geo
Compiling module: Std.Geo
Requested module: Std.Graphics2D
Requested module: Std.XML
Compiling module: Std.XML
Compiling module: Std.Graphics2D
Requested module: Std.MessagePack
Compiling module: Std.MessagePack
Requested module: Std.OAuth
Compiling module: Std.OAuth
Requested module: Std.Test
Compiling module: Std.Test
"Error while processing project settings: BreadcrumbDoesNotExistException (Breadcrumb {_items = [Definition {_nodeId = 573dff3a-45f8-44c2-8513-a9eb1e1862ce}]})"
INFO 2018-06-07T07:53:03.663023Z	:: sending ok for empire.graph.saveSettings.request
INFO 2018-06-07T07:53:03.663488Z	:: received empire.graph.saveSettings.response
INFO 2018-06-07T07:53:07.631955Z	:: received empire.graph.saveSettings.request
INFO empire.graph.saveSettings.request: Request {_location = GraphLocation {_filePath = "/tmp/luna28353/tutorials/USElectionPlayground/src/Main.luna", _breadcrumb = Breadcrumb {_items = [Definition {_nodeId = 573dff3a-45f8-44c2-8513-a9eb1e1862ce}]}}, _settings = LocationSettings {_visMap = Just (fromList [(TCons "Text" [],("LunaVisualizer: base: text","base/text/text.html")),(TCons "GeoJSONFeatureCollection" [],("LunaVisualizer: map: GeoJSON","map/geojson.html"))]), _camera = CameraTransformation {_screenToLogical = ( 3.846153846153846               0.0               0.0               0.0 )
(               0.0 3.846153846153846               0.0               0.0 )
(               0.0               0.0               1.0               0.0 )
( 745.1667116213463 -312.496058291916               0.0               1.0 )
, _logicalToScreen = (                0.26                 0.0                 0.0                 0.0 )
(                 0.0                0.26                 0.0                 0.0 )
(                 0.0                 0.0                 1.0                 0.0 )
( -193.74334502155006   81.24897515589817                 0.0                 1.0 )
, _lastInverse = 0}}}
"Error while processing project settings: BreadcrumbDoesNotExistException (Breadcrumb {_items = [Definition {_nodeId = 573dff3a-45f8-44c2-8513-a9eb1e1862ce}]})"
INFO 2018-06-07T07:53:07.670638Z	:: sending ok for empire.graph.saveSettings.request
INFO 2018-06-07T07:53:07.671227Z	:: received empire.graph.saveSettings.response
INFO 2018-06-07T07:53:13.444729Z	:: received empire.graph.collaboration.update
INFO 2018-06-07T07:53:13.447142Z	:: received empire.graph.collaboration.update
INFO 2018-06-07T07:53:13.509906Z	:: received empire.graph.node.updateMeta.request
INFO empire.graph.node.updateMeta.request: Request {_location = GraphLocation {_filePath = "/tmp/luna28353/tutorials/USElectionPlayground/src/Main.luna", _breadcrumb = Breadcrumb {_items = [Definition {_nodeId = 573dff3a-45f8-44c2-8513-a9eb1e1862ce}]}}, _updates = [(f8984e75-8f9f-4cb3-b67d-c2618244acf6,NodeMeta {_position = Position {fromPosition = Vector2 {_vector2_x = -208.0, _vector2_y = -208.0}}, _displayResult = False, _selectedVisualizer = Just ("LunaVisualizer: base: json","base/json/json.html")})]}
ERROR 2018-06-07T07:53:13.511705Z	:: error during processing request empire.graph.node.updateMeta.request: Breadcrumb {_items = [Definition {_nodeId = 573dff3a-45f8-44c2-8513-a9eb1e1862ce}]}
INFO 2018-06-07T07:53:13.515198Z	:: received empire.graph.node.updateMeta.response

**Comment by ljkania** [comment]
@lgawlik: Could you elaborate on this problem? What were you trying to do and how it failed (visually). It is much easier if you describe what did you do, what you wanted to achieve and what happened.
