### ISSUE TITLE
Server crashed

### ISSUE THREAD

**Issue by archonxgames** [luna/luna-studio#935]
Server crashed.

======= logs: =======

=== s-luna-empire.err.log ===
ERROR 2018-06-07T13:13:51.990998Z	:: error during processing request empire.graph.node.updateMeta.request: NodeDoesNotExistException 8a4d9d74-5250-4a72-9cc5-2cf12d097f7b
CallStack (from -prof):
ERROR 2018-06-07T13:13:57.0632829Z	:: error during processing request empire.graph.node.updateMeta.request: NodeDoesNotExistException 8a4d9d74-5250-4a72-9cc5-2cf12d097f7b
CallStack (from -prof):
ERROR 2018-06-07T13:13:57.8270067Z	:: error during processing request empire.graph.node.updateMeta.request: NodeDoesNotExistException 8a4d9d74-5250-4a72-9cc5-2cf12d097f7b
CallStack (from -prof):
ERROR couldn't remove directoryC:\Users\ULTIMU~1\AppData\Local\Temp\luna4036\unsaved-luna-project
luna-empire.exe: internal error: evacuate: strange closure type 2914
    (GHC version 8.0.2 for x86_64_unknown_mingw32)
    Please report this as a GHC bug:  http://www.haskell.org/ghc/reportabug

=== s-luna-empire.out.log ===
Requested module: Std.Base
Compiling module: Std.Base
Requested module: Std.HTTP
Compiling module: Std.HTTP
Requested module: Std.System
Compiling module: Std.System
Requested module: Std.Time
Compiling module: Std.Time
Requested module: Std.WebSockets
Compiling module: Std.WebSockets
Requested module: Std.Foreign
Requested module: Std.Foreign.C.Value
Compiling module: Std.Foreign.C.Value
Compiling module: Std.Foreign
"Error while processing project settings: AesonException \"Error in $: expected record (:*:), encountered Null\""

=== s-luna-empire.wrapper.log ===
2018-06-07 21:07:16,861 INFO  - Starting ServiceWrapper in the CLI mode
2018-06-07 21:07:17,617 INFO  - Completed. Exit code is 0

**Comment by sylwiabr** [comment]
Should be fixed in new packages (1.8)
