### ISSUE TITLE
Luna studio - Documentation, Forum, Chat buttons don't work

### ISSUE THREAD

**Issue by lgawlik** [luna/luna-studio#939]
In Luna studio, version downloaded from page, Linux->Documentation, Forum, Chat buttons don't work at all

**Comment by mikusp** [comment]
I checked this and it seems that `shell.openExternal` is not working as intended. `xdg-open URL` on the same machine works.

**Comment by mikusp** [comment]
I think it can be connected to https://github.com/electron/electron/issues/9998
