### ISSUE TITLE
Fix visualizer menu hover in basegl-ui

### ISSUE THREAD

**Issue by ljkania** [luna/luna-studio#948]
Hover on visualizers menu does not work well when is positioned in basegl `domLayer`. My guess is that it has something to do with @wdanilo magic to handle mouse properly. Menu is blinking and hover changes rapidly - there is no chance to click anything. This does not happens on other, manually added layers. Proposed solution: on mouse enter event move menu to higher layer and move it back on mouse leave.

**Comment by pmlodawski** [comment]
https://github.com/luna/luna-studio/issues/972 makes it html free so this problem disappears
