### ISSUE TITLE
Replace iframes with shadow doms in basegl-ui

### ISSUE THREAD

**Issue by ljkania** [luna/luna-studio#951]
In basegl-ui we are required to append iframe to different layer and this causes loosing its state. We should use shadowDOMs instead. @kustosz has more info about implementation.

**Comment by piotrMocz** [comment]
Shadow DOM doesn't play well with our version of Atom. After a bit of research conducted by @pmlodawski and myself, we decided to work on improving IFrames so that they don't blink.
