### ISSUE TITLE
Suspicious amount of memory allocation in the new GUI while zooming/panning.

### ISSUE THREAD

**Issue by piotrMocz** [luna/luna-studio#954]
This happens when I hold down the middle mouse button and move the mouse around continuously -- the memory slowly but surely goes up. In raw basegl it is more of a toothsaw pattern. Also, raw basegl allocates about 50MB constant while after a minute we can go as high as 600MB.

![Zrzut ekranu z 2018-06-22 13-57-15.png](https://images.zenhubusercontent.com/5967836b61b4ca3b0a74517c/f5e31048-1fc5-4593-afb1-e6b2fc2c59a5)![Zrzut ekranu z 2018-06-22 14-12-58.png](https://images.zenhubusercontent.com/5967836b61b4ca3b0a74517c/5b5d94d6-3280-45c8-8e57-686ded7dbf92)

**Comment by sylwiabr** [comment]
This is fixed by the heirarchical components model. Kudos @pmlodawski !
