### ISSUE TITLE
Unify the new styles (from basegl-ui) with the old ones.

### ISSUE THREAD

**Issue by sylwiabr** [luna/luna-studio#962]
The problem here is that the components inside `basegl-ui` have their own styles (in the basegl-ui repo). Atom knows nothing about these styles, though, as they are not concerning the `luna-studio` Atom plugin but one of its dependencies. This is why we kept copying them, directly in the `gen` directory in Atom. This is impossible now since we're now including `basegl-ui` as an npm package and its not part of our sources (nor should it).

The final solution is to unify the new styles with the existing ones for Luna Studio. During this process we could also clean up the styles a bit, as a lot of CSS classes has been rendered obsolete by the new gui (hence the rather generous estimate). This could be done during the general styling of the new gui.

**Comment by wdanilo** [comment]
I do not understand this issue tbh. 

1. We plan to go atomless.
2. Basegl does not use CSS styles, it uses some color-config file coffescript file.

Whats the point in "unifying" the styles? Basically I've got a plan to sit with @pmlodawski a week on making the new gui beautiful and we've got time slot for it planned on the timeline. What exactly is this task about?

**Comment by pmlodawski** [comment]
Basegl-ui does use css styles for HTML components like searcher or
breadcrumbs. These styles are in basegl-ui repo, but they need to be copied
to atom plugin and unified with atom styles

**Comment by piotrMocz** [comment]
We will patch the styles manually until we've got more time :(

**Comment by piotrMocz** [comment]
This is solved by using post-install hooks of the `luna-studio` atom package, see the branch `basegl-install` https://github.com/luna/luna-studio/tree/basegl-install
