### ISSUE TITLE
Error while spawning the searcher.

### ISSUE THREAD

**Issue by piotrMocz** [luna/luna-studio#963]
```
JavaScript exception: TypeError: Cannot read property 'setSelectionRange' of null
while processing: Shortcut (Event {_shortcut = SearcherOpen, _arg = Nothing})
```

This is something we have already seen, but I thought this got fixed by @ljkania 
Also, note that this happens in a package built from the `basegl-install` branch.
![error](https://user-images.githubusercontent.com/3109645/42282838-11b70318-7fa8-11e8-8aff-58a5c9b9c87a.png)

**Comment by ljkania** [comment]
Does it happen all the time? If not could you provide repro scenario?

**Comment by piotrMocz** [comment]
This is no longer happening, closing.
