### ISSUE TITLE
Improve visualization menu

### ISSUE THREAD

**Issue by pmlodawski** [luna/luna-studio#972]

**Comment by ljkania** [comment]
Is this issue finished? If so please move, if not comment what needs to be done to close it.

**Comment by piotrMocz** [comment]
+1 to what @ljkania said. If this is finished, let's close it. The menu seems to work, so I would be inclined towards closing the task. Further styling of the menu is a part of the "Look and feel effort".

@pmlodawski what's your stance?

**Comment by piotrMocz** [comment]
I can successfully select different visualisation types, so I would say it works. Styling is a different task, so I'm closing this one.
