### ISSUE TITLE
Error in LS while panning on MacOS

### ISSUE THREAD

**Issue by BinarySoftware** [luna/luna-studio#977]
Breadcrumb {_items = [Definition {_nodeId = 5d5e829f-679f-4a26-8e5d-b9d6b48fb7bd}]}

while processing event

empire.graph.node.updateMeta.response

======= logs: =======

=== luna-empire-stdout---supervisor-65AgB1.log ===
INFO 2018-07-19T11:03:56.56384Z	:: sending ok for empire.atom.file.open.request
INFO 2018-07-19T11:03:56.566661Z	:: received empire.atom.file.open.response
INFO 2018-07-19T11:03:56.639919Z	:: received empire.atom.file.get.request
INFO empire.atom.file.get.request: Request {_filePath = "/var/folders/26/z629yd7n0p5chdv_vnlrngjc0000gn/T/luna7628/tutorials/BasicsTutorial/src/Main.luna"}
INFO 2018-07-19T11:03:56.643777Z	:: sending response for empire.atom.file.get.request
INFO 2018-07-19T11:03:56.643777Z	:: Result {_code = "import Std.Base\nimport Std.Graphics2D\n\ndef halfCirc radius:\n    circle1 = circle radius\n    rectangle1 = rectangle 2.0*radius radius\n    translate1 = rectangle1 . translate 0.0 (-0.5 * radius)\n    difference1 = circle1 - translate1\n    difference1\n\ndef logoBody radius:\n    innerRadius = radius - 2.0\n    halfRadius = innerRadius / 2.0\n    halfCircle1 = halfCirc innerRadius\n    leftRadius = halfRadius + 4.0\n    circle1 = circle halfRadius\n    circle2 = circle leftRadius\n    translate2 = circle2 . translate -leftRadius 0.0\n    translate1 = circle1 . translate halfRadius 0.0\n    difference1 = halfCircle1 - translate2\n    sum1 = difference1 + translate1\n    sum1\n\ndef main:\n    radius = 32.0\n    innerRadius = 29.0\n    None\n"}
INFO 2018-07-19T11:03:56.676397Z	:: received empire.atom.file.get.response
INFO 2018-07-19T11:03:56.867332Z	:: received empire.graph.saveSettings.request
INFO empire.graph.saveSettings.request: Request {_location = GraphLocation {_filePath = "/var/folders/26/z629yd7n0p5chdv_vnlrngjc0000gn/T/luna7628/tutorials/BasicsTutorial/src/Main.luna", _breadcrumb = Breadcrumb {_items = [Definition {_nodeId = 5d5e829f-679f-4a26-8e5d-b9d6b48fb7bd}]}}, _settings = LocationSettings {_visMap = Just (fromList [(TCons "Geo" [],("LunaVisualizer: paper: centered","paper/paperCenter.html"))]), _camera = CameraTransformation {_screenToLogical = (  1.595307917888563                0.0                0.0                0.0 )
(                0.0  1.595307917888563                0.0                0.0 )
(                0.0                0.0                1.0                0.0 )
(  891.9178885630497 274.83284457478004                0.0                1.0 )
, _logicalToScreen = (  0.6268382352941176                 0.0                 0.0                 0.0 )
(                 0.0  0.6268382352941176                 0.0                 0.0 )
(                 0.0                 0.0                 1.0                 0.0 )
(  -559.0882352941176 -172.27573529411765                 0.0                 1.0 )
, _lastInverse = 0}}}
Requested module: Std.Geo
Compiling module: Std.Geo
Requested module: Std.MessagePack
Compiling module: Std.MessagePack
Requested module: Std.OAuth
Compiling module: Std.OAuth
Requested module: Std.Test
Compiling module: Std.Test
Requested module: Std.Geo
Compiling module: Std.Geo
Requested module: Std.MessagePack
Compiling module: Std.MessagePack
Requested module: Std.OAuth
Compiling module: Std.OAuth
Requested module: Std.Test
Compiling module: Std.Test
Requested module: Std.Geo
Compiling module: Std.Geo
Requested module: Std.MessagePack
Compiling module: Std.MessagePack
Requested module: Std.OAuth
Compiling module: Std.OAuth
Requested module: Std.Test
Compiling module: Std.Test
Requested module: Std.Geo
Compiling module: Std.Geo
Requested module: Std.MessagePack
Compiling module: Std.MessagePack
Requested module: Std.OAuth
Compiling module: Std.OAuth
Requested module: Std.Test
Compiling module: Std.Test
Requested module: Std.Geo
Compiling module: Std.Geo
Requested module: Std.MessagePack
Compiling module: Std.MessagePack
Requested module: Std.OAuth
Compiling module: Std.OAuth
Requested module: Std.Test
Compiling module: Std.Test
Requested module: Std.Geo
Compiling module: Std.Geo
Requested module: Std.MessagePack
Compiling module: Std.MessagePack
Requested module: Std.OAuth
Compiling module: Std.OAuth
Requested module: Std.Test
Compiling module: Std.Test
"Error while processing project settings: BreadcrumbDoesNotExistException (Breadcrumb {_items = [Definition {_nodeId = 5d5e829f-679f-4a26-8e5d-b9d6b48fb7bd}]})"
INFO 2018-07-19T11:03:56.888846Z	:: sending ok for empire.graph.saveSettings.request
INFO 2018-07-19T11:03:56.891608Z	:: received empire.graph.saveSettings.response
INFO 2018-07-19T11:03:57.010368Z	:: received empire.graph.saveSettings.request
INFO empire.graph.saveSettings.request: Request {_location = GraphLocation {_filePath = "/var/folders/26/z629yd7n0p5chdv_vnlrngjc0000gn/T/luna7628/tutorials/BasicsTutorial/src/Main.luna", _breadcrumb = Breadcrumb {_items = [Definition {_nodeId = 5d5e829f-679f-4a26-8e5d-b9d6b48fb7bd}]}}, _settings = LocationSettings {_visMap = Just (fromList [(TCons "Geo" [],("LunaVisualizer: paper: centered","paper/paperCenter.html"))]), _camera = CameraTransformation {_screenToLogical = (  1.595307917888563                0.0                0.0                0.0 )
(                0.0  1.595307917888563                0.0                0.0 )
(                0.0                0.0                1.0                0.0 )
(  891.9178885630497 274.83284457478004                0.0                1.0 )
, _logicalToScreen = (  0.6268382352941176                 0.0                 0.0                 0.0 )
(                 0.0  0.6268382352941176                 0.0                 0.0 )
(                 0.0                 0.0                 1.0                 0.0 )
(  -559.0882352941176 -172.27573529411765                 0.0                 1.0 )
, _lastInverse = 0}}}
"Error while processing project settings: BreadcrumbDoesNotExistException (Breadcrumb {_items = [Definition {_nodeId = 5d5e829f-679f-4a26-8e5d-b9d6b48fb7bd}]})"
INFO 2018-07-19T11:03:57.036625Z	:: sending ok for empire.graph.saveSettings.request
INFO 2018-07-19T11:03:57.042887Z	:: received empire.graph.saveSettings.response
INFO 2018-07-19T11:04:00.516686Z	:: received empire.graph.saveSettings.request
INFO empire.graph.saveSettings.request: Request {_location = GraphLocation {_filePath = "/var/folders/26/z629yd7n0p5chdv_vnlrngjc0000gn/T/luna7628/tutorials/BasicsTutorial/src/Main.luna", _breadcrumb = Breadcrumb {_items = [Definition {_nodeId = 5d5e829f-679f-4a26-8e5d-b9d6b48fb7bd}]}}, _settings = LocationSettings {_visMap = Just (fromList [(TCons "Geo" [],("LunaVisualizer: paper: centered","paper/paperCenter.html"))]), _camera = CameraTransformation {_screenToLogical = (  1.595307917888563                0.0                0.0                0.0 )
(                0.0  1.595307917888563                0.0                0.0 )
(                0.0                0.0                1.0                0.0 )
(  891.9178885630497 274.83284457478004                0.0                1.0 )
, _logicalToScreen = (  0.6268382352941176                 0.0                 0.0                 0.0 )
(                 0.0  0.6268382352941176                 0.0                 0.0 )
(                 0.0                 0.0                 1.0                 0.0 )
(  -559.0882352941176 -172.27573529411765                 0.0                 1.0 )
, _lastInverse = 0}}}
"Error while processing project settings: BreadcrumbDoesNotExistException (Breadcrumb {_items = [Definition {_nodeId = 5d5e829f-679f-4a26-8e5d-b9d6b48fb7bd}]})"
INFO 2018-07-19T11:04:00.569676Z	:: sending ok for empire.graph.saveSettings.request
INFO 2018-07-19T11:04:00.574349Z	:: received empire.graph.saveSettings.response
INFO 2018-07-19T11:04:21.797413Z	:: received empire.graph.collaboration.update
INFO 2018-07-19T11:04:43.461081Z	:: received empire.graph.node.updateMeta.request
INFO empire.graph.node.updateMeta.request: Request {_location = GraphLocation {_filePath = "/var/folders/26/z629yd7n0p5chdv_vnlrngjc0000gn/T/luna7628/tutorials/BasicsTutorial/src/Main.luna", _breadcrumb = Breadcrumb {_items = [Definition {_nodeId = 5d5e829f-679f-4a26-8e5d-b9d6b48fb7bd}]}}, _updates = [(ca7aebbf-9be2-464f-97d1-03516e185441,NodeMeta {_position = Position {fromPosition = Vector2 {_vector2_x = 1344.0, _vector2_y = 48.0}}, _displayResult = True, _selectedVisualizer = Just ("LunaVisualizer: paper: centered","paper/paperCenter.html")})]}
ERROR 2018-07-19T11:04:43.470083Z	:: error during processing request empire.graph.node.updateMeta.request: Breadcrumb {_items = [Definition {_nodeId = 5d5e829f-679f-4a26-8e5d-b9d6b48fb7bd}]}
INFO 2018-07-19T11:04:43.473871Z	:: received empire.graph.node.updateMeta.response

**Comment by sylwiabr** [comment]
@BinarySoftware can you tell us more about it? Can you reproduce it with Luna Studio 1.4?

**Comment by BinarySoftware** [comment]
No, actually I cannot reproduce it in 1.4, so I think that it is closed now
