### ISSUE TITLE
Libraries migration (Postgres, OpenCV, Lumeric)

### ISSUE THREAD

**Issue by lgawlik** [luna/luna-studio#981]
We have to check all of the existing libraries and check if they work properly. Specially:
- project structure
- methods names
- proper results

The list of existing libraries should be checked and noted (it will be the first step in this task).

Edit[@piotrMocz]:
The list of libraries is as follows:
- [x] Postgres
- [ ] OpenCV
- [x] Lumeric
- [x] Examples from the https://github.com/luna-packages repository

**Comment by mikusp** [comment]
@piotrMocz what's the status of this task?

**Comment by piotrMocz** [comment]
I was taking care of Lumeric and Postgres. Both work now: Lumeric is already merged and Postgres is under code review (https://github.com/luna/Postgres/pull/1) because I don't have push access ;) I can't even assign reviewers in that repo.

@sylwiabr was also refurbishing some libraries, IIRC.

**Comment by piotrMocz** [comment]
I updated the list of libraries, based on my knowledge of their status. Please correct it if you spot something wrong (especially if you are sure something works and I didn't put a checkmark there).

**Comment by piotrMocz** [comment]
I am closing this task: Lumeric, Postgres and examples do work. OpenCV is tracked in another task and therefore no longer part of this one.
