### ISSUE TITLE
[stability] State mismatch in graph coloring

### ISSUE THREAD

**Issue by kustosz** [luna/luna-studio#985]
It often happens with the new GUI that newly added nodes do not display their types or results. Doing any other change triggers coloring of those nodes. Backend logs indicate that the number of updates sent corresponds to the actual number of nodes, so it seems (though it's not 100% certain!) that GUI ignores these for some reason.
See video in the comment.

**Comment by kustosz** [comment]
Repro video. It is a freshly started Luna Studio. https://drive.google.com/open?id=1mlL4mLaZR4QjQI-ONI7DbRW_A70Ap5Hp

**Comment by pmlodawski** [comment]
It looks like, `NodeTypecheckerUpdate` and `NodeResultUpdate` arrives before `AddNodeResponse`. Detailed logs from gui below:

    UI (SearcherEvent (InputChanged "r" 1 1))
    UI (SearcherEvent (InputChanged "re" 2 2))
    UI (SearcherEvent Accept)
    Batch (UnknownEvent "empire.atom.file.substitute.update")
    Batch (UnknownEvent "empire.atom.file.substitute.update")
    Batch (NodeTypecheckerUpdate (Update {_location = GraphLocation {_filePath = "/tmp/luna26261/unsaved-luna-project/src/Main.luna", _breadcrumb = Breadcrumb {_items = [Definition {_nodeId = e9e5feb1-ecc8-430c-aac8-a45dd19cfb41}]}}, _node = InputSidebarUpdate {_tcNodeId = 75932242-d57e-4558-9493-342cd3944dec, _tcInputOutPorts = []}}))
    Batch (NodeTypecheckerUpdate (Update {_location = GraphLocation {_filePath = "/tmp/luna26261/unsaved-luna-project/src/Main.luna", _breadcrumb = Breadcrumb {_items = [Definition {_nodeId = e9e5feb1-ecc8-430c-aac8-a45dd19cfb41}]}}, _node = OutputSidebarUpdate {_tcNodeId = 8d4246e6-3b98-48a9-96f1-3720fd06eca9, _tcInPorts = LabeledTree {_subtrees = InPorts {_self = Nothing, _head = Nothing, _args = []}, _value = Port {_portId = [], _name = "output", _valueType = TCons "None" [], _state = WithDefault (Expression "Std.Base.None.None")}}}}))
    Batch (NodeTypecheckerUpdate (Update {_location = GraphLocation {_filePath = "/tmp/luna26261/unsaved-luna-project/src/Main.luna", _breadcrumb = Breadcrumb {_items = [Definition {_nodeId = e9e5feb1-ecc8-430c-aac8-a45dd19cfb41}]}}, _node = ExpressionUpdate {_tcNodeId = 0c5aaa65-8d57-478d-a324-25aa17c692aa, _tcInPorts = LabeledTree {_subtrees = InPorts {_self = Just (LabeledTree {_subtrees = InPorts {_self = Just (LabeledTree {_subtrees = InPorts {_self = Nothing, _head = Nothing, _args = []}, _value = Port {_portId = [Self,Self], _name = "self", _valueType = TStar, _state = NotConnected}}), _head = Nothing, _args = []}, _value = Port {_portId = [Self], _name = "self", _valueType = TCons "Text" [], _state = Connected}}), _head = Nothing, _args = []}, _value = Port {_portId = [], _name = "alias", _valueType = TCons "Text" [], _state = WithDefault (Expression "hello . reverse")}}, _tcOutPorts = LabeledTree {_subtrees = OutPorts [], _value = Port {_portId = [], _name = "reverse1", _valueType = TCons "Text" [], _state = NotConnected}}}}))
    Batch (NodeTypecheckerUpdate (Update {_location = GraphLocation {_filePath = "/tmp/luna26261/unsaved-luna-project/src/Main.luna", _breadcrumb = Breadcrumb {_items = [Definition {_nodeId = e9e5feb1-ecc8-430c-aac8-a45dd19cfb41}]}}, _node = ExpressionUpdate {_tcNodeId = fd7a622b-aabd-44ad-883b-7f702825639d, _tcInPorts = LabeledTree {_subtrees = InPorts {_self = Nothing, _head = Nothing, _args = []}, _value = Port {_portId = [], _name = "alias", _valueType = TCons "Text" [], _state = WithDefault (Constant (TextValue "Hello, World!"))}}, _tcOutPorts = LabeledTree {_subtrees = OutPorts [], _value = Port {_portId = [], _name = "hello", _valueType = TCons "Text" [], _state = NotConnected}}}}))
    Batch (NodeResultUpdate (Update {_location = GraphLocation {_filePath = "/tmp/luna26261/unsaved-luna-project/src/Main.luna", _breadcrumb = Breadcrumb {_items = [Definition {_nodeId = e9e5feb1-ecc8-430c-aac8-a45dd19cfb41}]}}, _nodeId = 0c5aaa65-8d57-478d-a324-25aa17c692aa, _value = NodeValue "!dlroW ,olleH" (Just (Value "\"!dlroW ,olleH\"")), _execTime = 0}))
    Batch (NodeResultUpdate (Update {_location = GraphLocation {_filePath = "/tmp/luna26261/unsaved-luna-project/src/Main.luna", _breadcrumb = Breadcrumb {_items = [Definition {_nodeId = e9e5feb1-ecc8-430c-aac8-a45dd19cfb41}]}}, _nodeId = fd7a622b-aabd-44ad-883b-7f702825639d, _value = NodeValue "Hello, World!" (Just (Value "\"Hello, World!\"")), _execTime = 0}))
    Batch (AddNodeResponse (Response {_requestId = 048c331a-41d8-4027-b974-fdab296c20f7, _guiID = Just 53d72c8f-a8cc-57b5-9c7b-b2cd326c3501, _request = Request {_location = GraphLocation {_filePath = "/tmp/luna26261/unsaved-luna-project/src/Main.luna", _breadcrumb = Breadcrumb {_items = [Definition {_nodeId = e9e5feb1-ecc8-430c-aac8-a45dd19cfb41}]}}, _nodeLoc = NodeLoc {_path = NodePath {_localBc = Breadcrumb {_items = []}}, _nodeId = 0c5aaa65-8d57-478d-a324-25aa17c692aa}, _expression = "reverse ", _nodeMeta = NodeMeta {_position = Position {fromPosition = Vector2 {_vector2_x = 176.0, _vector2_y = 0.0}}, _displayResult = False, _selectedVisualizer = Nothing}, _connectTo = Just fd7a622b-aabd-44ad-883b-7f702825639d}, _inverse = Ok {_resultData = ()}, _status = Ok {_resultData = Diff {_reversedModifications = [AddConnection (ModificationAddConnection {_newConnection = Connection {_src = OutPortRef {_srcNodeLoc = NodeLoc {_path = NodePath {_localBc = Breadcrumb {_items = []}}, _nodeId = fd7a622b-aabd-44ad-883b-7f702825639d}, _srcPortId = []}, _dst = InPortRef {_dstNodeLoc = NodeLoc {_path = NodePath {_localBc = Breadcrumb {_items = []}}, _nodeId = 0c5aaa65-8d57-478d-a324-25aa17c692aa}, _dstPortId = [Self]}}}),AddNode (ModificationAddNode {_newNode = ExpressionNode {_exprNodeId = 0c5aaa65-8d57-478d-a324-25aa17c692aa, _expression = "\8226 . reverse", _isDefinition = False, _name = Just "reverse1", _code = "hello . reverse", _inPorts = LabeledTree {_subtrees = InPorts {_self = Just (LabeledTree {_subtrees = InPorts {_self = Just (LabeledTree {_subtrees = InPorts {_self = Nothing, _head = Nothing, _args = []}, _value = Port {_portId = [Self,Self], _name = "self", _valueType = TStar, _state = NotConnected}}), _head = Nothing, _args = []}, _value = Port {_portId = [Self], _name = "self", _valueType = TStar, _state = Connected}}), _head = Nothing, _args = []}, _value = Port {_portId = [], _name = "alias", _valueType = TStar, _state = WithDefault (Expression "hello . reverse")}}, _outPorts = LabeledTree {_subtrees = OutPorts [], _value = Port {_portId = [], _name = "reverse1", _valueType = TStar, _state = NotConnected}}, _nodeMeta = NodeMeta {_position = Position {fromPosition = Vector2 {_vector2_x = 176.0, _vector2_y = 0.0}}, _displayResult = False, _selectedVisualizer = Nothing}, _canEnter = False}})]}}}))
